SmartThingsCommunity/smartthings-cli

- package-lock.json
- packages/cli/README.md
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/commands/devices.ts
- packages/cli/src/commands/installedapps.ts
- packages/cli/src/lib/api-helpers.ts
Adds a verbose flag for installedapps that includes the location name and for devices that includes the location and room names.
> Location and room injection for installedapps and devices

- packages/cli/src/commands/schema.ts
- packages/cli/src/commands/schema/create.ts
- packages/cli/src/commands/schema/delete.ts
- packages/cli/src/commands/schema/update.ts
- packages/cli/src/lib/aws-utils.ts
Added basic list, get, create, update, and delete commands for ST Schema connectors
> PI-900 Added ST Schema commands

- README.md
Minor changes to alert users to the location of the binaries
> Make it more clear where the binaries are

- packages/cli/README.md
- packages/cli/src/commands/capabilities.ts
- packages/cli/src/commands/locations/rooms.ts
Created rooms command to display a list of the rooms when called with no id. Users can also call the rooms command with an roomId or index from the table to display a particular room's information. If the command is called with a locationId, the rooms of that location will be listed. 
I also updated the readme for the schema commands, installedapps:delete command, and room command.
> create rooms command

- packages/cli/README.md
- packages/cli/src/commands/locations/rooms/create.ts
Added rooms:create command. Users can now create rooms using a locationId and a form of input.
> add rooms:create command

- packages/cli/README.md
- packages/cli/src/commands/locations/rooms/delete.ts
Added rooms:delete command. Users can now delete rooms using the roomId and locationId. If no roomId is included, a table containing all of the rooms will be outputted and users can choose which room to be deleted by index or roomId.
> add rooms:delete command

- packages/cli/README.md
- packages/cli/src/commands/locations/rooms/create.ts
- packages/cli/src/commands/locations/rooms/update.ts
- packages/cli/src/commands/locations/update.ts
Added rooms:update command. Users can now update rooms using the roomId, a form of input, and the locationId.
> add rooms:update

- packages/cli/src/commands/capabilities/create.ts
- add ability to specify which namespace to create capabilities under if the namespace exists already
> feat: add namespace flag to capabilities create

- packages/cli/README.md
- packages/lib/src/login-authenticator.ts
Updated scopes for PKCE auth flow to new controller scope. Also fixed a couple of minor bugs in implementation.
> update to use controller scope

- README.md
- packages/cli/README.md
- packages/cli/doc/configuration.md
- packages/cli/src/commands/locations.ts
- packages/cli/src/commands/locations/create.ts
I added a little more documentation, especially for configuration.
> add configuration documentation

- README.md
- bootstrap.sh
- package-lock.json
- package.json
* install latest core-sdk via npm install
* update dev scripts and instructions for linking local changes
> chore: install core-sdk and update manual link

- packages/lib/README.md
- packages/lib/package.json
- packages/testlib/README.md
- added missing dependencies
- updated READMEs a little (they still need work)
> bug: add missing dependencies

- lerna.json
- publish.sh
* add initial script for a local verification before publishing
> chore: add lerna publish script

- .gitignore
- packages/cli/README.md
- packages/cli/src/commands/devices.ts
- packages/cli/src/commands/locations/delete.ts
- packages/lib/src/api-command.ts
- packages/lib/src/io-command.ts
* added support for getting input from command line options by implementing `getInputFromCommandLine` and `hasCommandLineInput` to `Inputting` mixin
* a little minor clean-up
> feat: add support for building input form command line options

- packages/lib/src/login-authenticator.ts
* create directory necessary for class on init (noop if already exists)
* refactor read method to maintain current functionality while improving robustness to external filesystem changes
> fix(LoginAuthenticator): create cli dir on init

- publish.sh
* update publish script to use pi-bot github user
> build: update publish script to use pi-bot github user

- packages/lib/src/io-command.ts
- added more detailed comments on the various APICommand classes
> docs(lib): add more detailed comments on the various APICommand classes

- package-lock.json
- package.json
- packages/cli/package.json
- packages/lib/package.json
Bump core-sdk and log4js versions.
> fix: bump core-sdk and log4js versions

- packages/lib/src/__tests__/logger.test.ts
- packages/lib/src/logger.ts
* added unit tests for logger.ts
* fixed minor bug with `level` property (get) on a logger that was discovered by tests
* removed a couple of `any` uses
> test: add unit tests for logger

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/src/commands/apps/authorize.ts
- packages/cli/src/commands/schema/authorize.ts
- packages/cli/src/lib/generate-command.ts
- packages/lib/package-lock.json
- packages/lib/src/__tests__/logger.test.ts
- packages/lib/src/logger.ts
* updated core SDK version
* removed unused ambiguous `log` method
* fixed a couple of lint errors
* ran `npm audit fix`
* fixed one error that showed up after `npm audit fix`
> fix: remove ambiguous log method

- packages/cli/README.md
- packages/cli/src/commands/capabilities/translations.ts
- packages/cli/src/commands/capabilities/translations/upsert.ts
- packages/cli/src/commands/deviceprofiles/translations.ts
- packages/cli/src/commands/deviceprofiles/translations/delete.ts
- packages/cli/src/commands/deviceprofiles/translations/upsert.ts
- packages/lib/src/io-command.ts
Note that these localizations are lists nested in the primary, listable capability and device profile objects and therefore required new command base classes to support selection from lists by index.
> feat: added device profile and capability localizations

- packages/lib/src/__tests__/util.test.ts
- packages/lib/src/util.ts
* also small whitespace edits for readability
> test(applyMixins): add cases for properties and advanced functions

- packages/lib/src/__tests__/util.test.ts
* edit test that was erroneously taking a wrong branch, thus decreasing code coverage
> test(applyMixins): fix async merge to improve code coverage

- package-lock.json
- packages/cli/README.md
- packages/cli/src/commands/apps.ts
- packages/cli/src/commands/devices.ts
Added `--installed-app-id` options to devices list that shows only devices created by that installed app instance
> feat: Added option to filter devices by installedAppId

- .gitignore
- .release-it.yaml
- package-lock.json
- package.json
- publish.sh
* resolve issue where built binaries version output was one behind than the release version
* use `release-it` to update Github release with zipped binaries automatically
> CI(publish): fix order of version/pkg, automate zip upload

- packages/lib/src/__tests__/input-builder.test.ts
- packages/lib/src/__tests__/output-builder.test.ts
- packages/lib/src/output-builder.ts
- packages/lib/src/smartthings-command.ts
* added unit tests for output-builder.ts functionality
* fixed bug where indent was not checked from config file
> test: add unit tests for output-builder.ts

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/hooks/init/init-config.ts
- packages/lib/jest.config.js
- packages/lib/src/__tests__/logger.test.ts
- packages/lib/src/logger.ts
* write `smartthings.log` to [oclif CLI cache directory](https://oclif.io/docs/config) by default
* enforce max file size of 1MB to default log
* resolve a couple of lerna/jest related warnings
> feat(logger): default log file path to oclif cacheDir

- packages/cli/src/commands/capabilities/create.ts
* Added validation for both attribute and command names, requiring them to be max 36 characters, only letters and start with a lowercase letter.
* If the user enters an attribute name longer than 33 characters, allow them to enter a shorter one or acknowledge they will not need a setter since prepending the attribute name with `set` to make a setter name would violate the requirements for the name of the command for the setter.
> fix: validate capability command and attribute names

- packages/cli/README.md
- packages/cli/doc/configuration.md
* fix broken links in cli README
> docs: add context for default log cache

- package-lock.json
- packages/cli/package.json
- packages/cli/src/commands/deviceprofiles/device-config.ts
- packages/cli/src/commands/deviceprofiles/view.ts
- packages/lib/package.json
Added support for device presentations with manufacturerName (mnmn) values other than the default "SmartThingsCommunity" one. This change is needed to be able to read dev workspace created device configs.
> fix: Added support for device presentation manufacturer name

- package-lock.json
- package.json
- packages/cli/global.d.ts
- packages/cli/jest.config.js
- packages/lib/global.d.ts
- packages/lib/jest.config.js
- packages/lib/src/__tests__/basic-io.test.ts
- packages/lib/src/basic-io.ts
- packages/testlib/global.d.ts
- packages/testlib/jest.config.js
* call `InputProcessor` methods in the correct order
* added `jest-extended` (for `toHaveBeenCalledBefore` test)
* updated tests
> fix: correct ordering of InputProcessor calls

- packages/cli/README.md
- packages/cli/src/commands/locations/rooms.ts
- packages/cli/src/commands/locations/rooms/delete.ts
- packages/cli/src/commands/locations/rooms/update.ts
Fixed a couple of flags that were using camel case to use kebab case.
> fix: use kebab case for all flags

- packages/cli/README.md
This is just an update to the README made by running `lerna run readme`.
> docs: update README from code

- packages/cli/src/commands/apps/delete.ts
- packages/cli/src/commands/apps/register.ts
- packages/cli/src/commands/capabilities.ts
- packages/cli/src/commands/capabilities/delete.ts
- packages/cli/src/commands/deviceprofiles/delete.ts
- packages/cli/src/commands/devices/delete.ts
- packages/cli/src/commands/locations/delete.ts
- packages/cli/src/commands/locations/rooms/delete.ts
- packages/cli/src/commands/rules/delete.ts
- packages/cli/src/commands/schema/create.ts
- packages/cli/src/commands/schema/delete.ts
- packages/lib/src/__tests__/acting-io.test.ts
- packages/lib/src/acting-io.ts
- packages/lib/src/io-command.ts
> refactor: replace SelectingApiCommand with functions

- packages/cli/README.md
- packages/cli/src/commands/devices/commands.ts
- packages/cli/src/commands/locations/create.ts
- packages/lib/src/__tests__/acting-io.test.ts
- packages/lib/src/__tests__/basic-io.test.ts
- packages/lib/src/__tests__/input-builder.test.ts
- packages/lib/src/__tests__/input.test.ts
- packages/lib/src/__tests__/resources/good-config.yaml
- packages/lib/src/acting-io.ts
- packages/lib/src/basic-io.ts
- packages/lib/src/input-builder.ts
- packages/lib/src/input.ts
> refactor: convert devices:commands to functional style and some cleanup

- packages/lib/src/io-command.ts
> refactor: remove references to SelectingApiCommand

- packages/lib/src/__mocks__/logger.ts
- packages/lib/src/__tests__/api-command.test.ts
- packages/lib/src/__tests__/cli-config.test.ts
- packages/lib/src/__tests__/table-generator.test.ts
- packages/lib/src/__tests__/test-lib/mock-logger.ts
- packages/lib/src/api-command.ts
- packages/lib/src/logger.ts
Finished filling in a few gaps for files that were already mostly tested.
> tests: fill in some testing gaps

- packages/cli/src/commands/deviceprofiles/presentation.ts
- packages/cli/src/commands/devices/presentation.ts
- packages/cli/src/commands/presentation.ts
- packages/cli/src/commands/presentation/device-config.ts
- packages/lib/src/io-command.ts
> refactor: replace OutputApiCommand with functions

- packages/cli/jest.config.js
- packages/cli/src/__tests__/commands/presentation/device-config.test.ts
- packages/cli/src/__tests__/setup/jest.setup.ts
- packages/testlib/package.json
- packages/testlib/src/index.ts
- packages/testlib/src/test-setup.ts
> test(presentation): import setup file from testlib

- packages/testlib/README.md
- packages/testlib/jest.setup.ts.example
- packages/testlib/src/test-setup.ts
> docs: add jest setup instructions

- packages/cli/README.md
- packages/cli/src/__tests__/commands/devices.test.ts
- packages/cli/src/commands/deviceprofiles/translations/upsert.ts
- packages/cli/src/commands/deviceprofiles/update.ts
- packages/cli/src/commands/deviceprofiles/view.ts
- packages/cli/src/commands/deviceprofiles/view/update.ts
- packages/cli/src/commands/devices.ts
- packages/cli/src/commands/devices/capability-status.ts
- packages/cli/src/commands/devices/component-status.ts
- packages/cli/src/commands/devices/health.ts
- packages/cli/src/commands/devices/presentation.ts
- packages/cli/src/commands/devices/status.ts
- packages/cli/src/commands/devices/update.ts
- packages/cli/src/commands/locations.ts
- packages/cli/src/commands/locations/delete.ts
- packages/cli/src/commands/locations/rooms.ts
- packages/cli/src/commands/locations/rooms/delete.ts
- packages/cli/src/commands/locations/rooms/update.ts
- packages/cli/src/commands/locations/update.ts
- packages/cli/src/commands/rules/update.ts
- packages/cli/src/commands/schema/update.ts
- packages/lib/src/io-command.ts
* updated the last of the `SelectingInputOutputAPICommand` and removed it
* removed some other methods made unused in previous commits
* added a few tests to a single command
> refactor: convert rest of SelectingInputOutputAPICommand commands to functional version

- packages/cli/README.md
- packages/cli/src/commands/apps.ts
- packages/cli/src/commands/capabilities.ts
- packages/cli/src/commands/capabilities/delete.ts
- packages/cli/src/commands/capabilities/presentation/create.ts
- packages/cli/src/commands/capabilities/presentation/update.ts
- packages/cli/src/commands/capabilities/translations/upsert.ts
- packages/cli/src/commands/capabilities/update.ts
- packages/cli/src/commands/deviceprofiles.ts
- packages/cli/src/commands/devices.ts
- packages/lib/src/__tests__/command-util.test.ts
- packages/lib/src/basic-io.ts
- packages/lib/src/command-util.ts
- packages/lib/src/io-command.ts
- packages/lib/src/smartthings-command.ts
* updated commands using `SelectingInputOutputAPICommandBase` to the functional versions
* removed `SelectingInputOutputAPICommandBase`
> refactor: convert SelectingInputOutputAPICommandBase commands to functional version

- packages/cli/README.md
- packages/lib/src/__tests__/output.test.ts
- packages/lib/src/io-util.ts
- packages/lib/src/output.ts
> feat: output JSON by default when not outputting to the console

- packages/lib/src/__tests__/login-authenticator.test.ts
- packages/lib/src/login-authenticator.ts
* added unit tests for `LoginAuthenticator` class
* fixed a couple of minor issues found
> tests: add unit tests for login-authenticator

- .github/workflows/ci-cd.yml
- package-lock.json
- package.json
* update `lerna` to 4.0.0 which resolved failures in Windows bootstrapping
* update to `actions/setup-node@v2` which uses cached LTS versions on the runners
* isolate linting to ubuntu runner for speed and reliability
> ci: fix Windows runner

- packages/lib/package.json
- packages/lib/src/__tests__/login-authenticator.test.ts
- packages/lib/src/__tests__/sse-command.test.ts
- packages/lib/src/sse-command.ts
* include `@types/eventsource` in dependencies so that consuming projects do not need to install separately
* fix code verifier regex in unit test for login authenticator
> feat: accept eventsource init dict

- .release-it.yaml
- package-lock.json
- package.json
- packages/cli/package.json
- packages/lib/package.json
- packages/testlib/package.json
* pull release-it into top level dev dependencies as it it used with lerna
> ci(release-it): disable required upstream branch

- package-lock.json
> build(package-lock): push missed changes

- packages/lib/package.json
> fix(deps): include cli-ux as dependency

- packages/lib/src/__tests__/sse-command.test.ts
- packages/lib/src/sse-command.ts
> feat: log errors from source handler

- package-lock.json
- packages/cli/package.json
- packages/cli/src/commands/capabilities/presentation.ts
- packages/cli/src/commands/deviceprofiles.ts
- packages/cli/src/commands/deviceprofiles/create.ts
- packages/cli/src/commands/deviceprofiles/delete.ts
- packages/cli/src/commands/deviceprofiles/device-config.ts
- packages/cli/src/commands/deviceprofiles/presentation.ts
- packages/cli/src/commands/deviceprofiles/publish.ts
- packages/cli/src/commands/deviceprofiles/translations.ts
- packages/cli/src/commands/deviceprofiles/translations/delete.ts
- packages/cli/src/commands/deviceprofiles/translations/upsert.ts
- packages/cli/src/commands/deviceprofiles/update.ts
- packages/cli/src/commands/deviceprofiles/view.ts
- packages/cli/src/commands/deviceprofiles/view/create.ts
- packages/cli/src/commands/deviceprofiles/view/update.ts
- packages/cli/src/commands/presentation.ts
- packages/cli/src/commands/presentation/device-config.ts
- packages/lib/package.json
* Added a summary of new device preferences info to common output for device profiles.
* Added note about info being summarized (and updated wording a bit). We will revisit this again in another issue.
* Included "device-profiles" aliases for all "deviceprofiles" subcommands.
> feat: add device preferences output to device profiles

- package-lock.json
- package.json
- packages/cli/package.json
- packages/cli/src/commands/capabilities/translations/create.ts
- packages/cli/src/commands/capabilities/translations/update.ts
- packages/lib/package.json
* added `create` and `update` commands under `capabilities:translations`
* updated upstream version of core-sdk
> fix: fixes to capability translations

- package-lock.json
- packages/cli/package.json
- packages/lib/package.json
- packages/lib/src/__tests__/login-authenticator.test.ts
- packages/lib/src/login-authenticator.ts
- packages/lib/src/sse-command.ts
> feat(LoginAuthenticator): provide generic auth method

- package-lock.json
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/commands/capabilities/create.ts
- packages/cli/src/commands/devices/preferences.ts
- packages/lib/package.json
Added command to retrieve device preference values. Also updated capability interactive creation to prompt for units of measure for integer and number attribute types
> feat: Added device preferences and capability units

- .github/ISSUE_TEMPLATE/question_template.md
> docs: remove mention of SDK from template

- packages/lib/src/__tests__/login-authenticator.test.ts
- packages/lib/src/login-authenticator.ts
* reset `authenticationInfo` to undefined before logging in
* added a bit better error handling so we don't have to wait for a timeout when we know an error has ocurred
* added missing unit test for logout
> fix: reset authenticationInfo before login, handle error cases better

- packages/lib/src/basic-io.ts
add documentation to `Naming` and `Sorting` interfaces
> docs: add documentation to Naming and Sorting interfaces

- packages/lib/src/sse-io.ts
> fix: narrow type accepted by event logger

- packages/cli/src/commands/deviceprofiles/presentation.ts
Change to allow deviceprofiles:presentation to accept output formal flags
> fix: Added output format flags to deviceprofiles:presentation

- package-lock.json
- packages/cli/README.md
- packages/cli/package.json
Bake the edge CLI plugin into the CLI.
> feat: add edge commands plugin

- package-lock.json
- packages/cli/package.json
Version 1.0.5 of edge plugin includes two bug fixes.
> fix: bump edge plugin version to 1.0.5

- packages/lib/src/sse-command.ts
> fix(SseCommand): call base Command init

- package-lock.json
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/commands/schema/regenerate.ts
- add ability to assign and install to edge:drivers:package command
- verify host on first request in edge:logcat command
- add support for building and uploading edge drivers separately
> update edge plugin to version 1.3

- packages/cli/src/__tests__/commands/locations.test.ts
- packages/cli/src/__tests__/commands/locations/create.test.ts
- packages/cli/src/__tests__/commands/locations/delete.test.ts
- packages/cli/src/__tests__/commands/locations/update.test.ts
> test: add test coverage for location commands

- packages/cli/src/__tests__/commands/locations/rooms.test.ts
- packages/cli/src/__tests__/commands/locations/rooms/create.test.ts
- packages/cli/src/__tests__/commands/locations/rooms/delete.test.ts
- packages/cli/src/__tests__/commands/locations/rooms/update.test.ts
- packages/cli/src/__tests__/lib/commands/locations/rooms/rooms-util.test.ts
- packages/cli/src/commands/locations/rooms.ts
- packages/cli/src/commands/locations/rooms/create.ts
- packages/cli/src/commands/locations/rooms/delete.ts
- packages/cli/src/commands/locations/rooms/update.ts
- packages/cli/src/commands/schema/update.ts
- packages/cli/src/lib/aws-utils.ts
- packages/cli/src/lib/commands/locations/rooms/rooms-util.ts
- export room utils from new cli/lib module
> test: add unit test coverage for rooms commands

- packages/cli/src/__tests__/commands/apps/oauth.test.ts
- packages/cli/src/__tests__/commands/apps/oauth/generate.test.ts
- packages/cli/src/__tests__/commands/apps/oauth/update.test.ts
- packages/cli/src/commands/apps/create.ts
- packages/cli/src/commands/apps/oauth.ts
- packages/cli/src/commands/apps/oauth/generate.ts
- packages/cli/src/commands/apps/oauth/update.ts
- packages/cli/src/commands/apps/register.ts
- packages/cli/src/commands/apps/settings.ts
- packages/cli/src/commands/apps/settings/update.ts
- packages/cli/src/commands/apps/update.ts
- packages/cli/src/lib/aws-utils.ts
- fix a few mistakes in command descriptions
> test: add test coverage for apps:oauth commands

- package-lock.json
- packages/cli/package.json
- packages/lib/package.json
- packages/lib/src/__tests__/login-authenticator.test.ts
- packages/lib/src/logger.ts
- packages/lib/src/login-authenticator.ts
> fix: scrub sensitive info from logging

- packages/cli/README.md
- packages/cli/package.json
> docs: include lerna package dir in code links

- packages/cli/README.md
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **[CONTRIBUTING](../CONTRIBUTING.md)** document
> Updating PAT token link in CLI README

- packages/cli/src/commands/deviceprofiles/device-config.ts
> refactor: fix typos in profile config command

- package-lock.json
- packages/cli/package.json
- packages/cli/src/__tests__/commands/devicepreferences/translations.test.ts
- packages/cli/src/__tests__/commands/devicepreferences/translations/create.test.ts
- packages/cli/src/commands/capabilities/translations.ts
- packages/cli/src/commands/devicepreferences.ts
- packages/cli/src/commands/devicepreferences/create.ts
- packages/cli/src/commands/devicepreferences/translations.ts
- packages/cli/src/commands/devicepreferences/translations/create.ts
- packages/cli/src/commands/devicepreferences/update.ts
- packages/cli/src/lib/commands/devicepreferences/devicepreferences-util.ts
- packages/cli/src/lib/commands/devicepreferences/translations/translations-util.ts
- packages/lib/package.json
- packages/testlib/package.json
- extract common logic to util lib
- bump some oclif deps
> feat(devicepreferences): initial suppport for i18n

- package-lock.json
- packages/cli/package.json
- packages/lib/package.json
- packages/lib/src/sse-command.ts
- bump @smartthings/plugin-cli-edge
- (lib) bump axios to non-vulnerable minor version
> feat(edge): debug logging in logcat

- package-lock.json
- packages/cli/package.json
- packages/cli/src/__tests__/commands/devices.test.ts
- packages/cli/src/__tests__/lib/commands/devices/devices-util.test.ts
- packages/cli/src/commands/capabilities/presentation.ts
- packages/cli/src/commands/deviceprofiles.ts
- packages/cli/src/commands/devices.ts
- packages/cli/src/commands/devices/capability-status.ts
- packages/cli/src/commands/devices/component-status.ts
- packages/cli/src/commands/devices/health.ts
- packages/cli/src/commands/devices/preferences.ts
- packages/cli/src/commands/devices/presentation.ts
- packages/cli/src/commands/devices/rename.ts
- packages/cli/src/commands/devices/status.ts
- packages/cli/src/commands/devices/update.ts
- packages/cli/src/commands/presentation/device-config.ts
- packages/cli/src/lib/commands/devices/devices-util.ts
- packages/lib/package.json
- packages/lib/src/__tests__/login-authenticator.test.ts
- packages/lib/src/table-generator.ts
- packages/testlib/package.json
- tsconfig.json
* updated output of `devices <device-id-or-index>` to include detail about drivers
* updated some libraries (core SDK, cli-table)
* updated TypeScript version
* refactored a couple of common functions into `*-utils` and unit tested them
* fleshed out unit tests for `devices` command
* added "this is summarized" message to default devices output
> feat: update standard device details output

- package-lock.json
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/__tests__/commands/devicepreferences/translations.test.ts
- packages/cli/src/__tests__/commands/devicepreferences/translations/update.test.ts
- packages/cli/src/commands/devicepreferences/translations.ts
- packages/cli/src/commands/devicepreferences/translations/update.ts
- packages/lib/package.json
> feat(devicepreferences): expanded i18n support

- package-lock.json
- packages/cli/README.md
- packages/cli/jest.config.js
- packages/cli/package.json
- packages/cli/src/__tests__/commands/deviceprofiles.test.ts
- packages/cli/src/__tests__/commands/rules.test.ts
- packages/cli/src/__tests__/commands/rules/create.test.ts
- packages/cli/src/__tests__/commands/rules/delete.test.ts
- packages/cli/src/__tests__/commands/rules/execute.test.ts
- packages/cli/src/__tests__/commands/rules/update.test.ts
- packages/cli/src/__tests__/lib/commands/rules/rules-util.test.ts
- packages/cli/src/commands/rules.ts
- packages/cli/src/commands/rules/create.ts
- packages/cli/src/commands/rules/delete.ts
- packages/cli/src/commands/rules/execute.ts
- packages/cli/src/commands/rules/update.ts
- packages/cli/src/lib/commands/rules/rules-util.ts
- packages/lib/jest.config.js
- packages/lib/package.json
- packages/testlib/jest.config.js
* added `rules:execute` command
* some light refactoring of functions used by rules commands to match current standards
* added unit tests for all rules commands and the refactored utilities for them
* updated rules for tests to produce cleaner code coverage output
> feat: add rules:execute command

- packages/cli/README.md
- packages/cli/doc/configuration.md
Updated readme and configuration file documentation files.
> docs: Updated configuration file definition to include org key

- package-lock.json
- package.json
- packages/cli/README.md
- packages/cli/doc/configuration.md
- packages/cli/package.json
- packages/lib/package.json
- packages/lib/src/input.ts
- packages/lib/src/output-builder.ts
* hide uncommon flags from help to reduce clutter in README and help
* updated configuration README to describe flags omitted
* bumped core SDK version
> feat: hide uncommon flags from help to reduce clutter

- package-lock.json
Reverted package-lock.json to previous version so the built binary will work again.
> fix: revert package-lock.json which had been rebuilt from scratch

- packages/lib/src/__tests__/api-command.test.ts
- packages/lib/src/api-command.ts
* added warning logger to log warning headers if they are present
* fleshed out unit tests for `APICommand`
> feat: log warning headers when present

- bootstrap.sh
- package-lock.json
- packages/cli/README.md
- packages/cli/package.json
> fix(edge): bump plugin-cli-edge to 1.8.1

- packages/cli/doc/configuration.md
- packages/cli/src/__tests__/commands/devices.test.ts
- packages/cli/src/commands/capabilities.ts
- packages/cli/src/commands/devicepreferences.ts
- packages/cli/src/commands/deviceprofiles.ts
- packages/cli/src/commands/devices.ts
- packages/cli/src/commands/presentation.ts
- packages/lib/src/__tests__/api-helpers.test.ts
- packages/lib/src/api-helpers.ts
* added "type" filter to devices command
* added note about merge keys not being supported in current version of YAML
* refactor `forAllOrganizations` utility method to include cloning or client for the user
> feat: add type filter to devices command; minor refactoring

- packages/cli/README.md
- packages/cli/src/commands/devicepreferences/create.ts
> fix(devicepreferences): make create prompts more clear

- .github/workflows/release.yaml
> build(changesets): disable github releases

- .changeset/chilly-chicken-taste.md
- package-lock.json
- packages/cli/package.json
Updated edge plugin to get compatible version and pull in new save default hub/channel feature.
> feat: support saving default hub and channel

- .changeset/smart-meals-hammer.md
- package-lock.json
- packages/cli/package.json
- packages/lib/package.json
- packages/testlib/package.json
* updated `pkg`
* build binaries with Node 16
* moved some config from command line into JSON
> build: update pkg and build binary with node 16

- package-lock.json
- packages/cli/src/__tests__/commands/apps.test.ts
- packages/cli/src/__tests__/lib/commands/apps/apps-util.test.ts
- packages/cli/src/__tests__/lib/commands/devices/devices-util.test.ts
- packages/cli/src/commands/apps.ts
- packages/cli/src/lib/commands/apps/apps-util.ts
> test(apps): finish todo unit tests

- .changeset/moody-fishes-protect.md
- package-lock.json
- package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/testlib/package.json
> fix: bump @smartthings/plugin-cli-edge

- .eslintrc.js
- package-lock.json
- packages/cli/package.json
- packages/cli/src/__tests__/commands/rules/execute.test.ts
- packages/cli/src/__tests__/lib/commands/rules/rules-util.test.ts
- packages/cli/src/commands/devices/commands.ts
- packages/cli/src/commands/rules/execute.ts
- packages/cli/src/lib/commands/rules/rules-util.ts
- packages/lib/package.json
- packages/testlib/package.json
* update core SDK version and make necessary updates
> refactor: update core SDK version

- .changeset/blue-carrots-remember.md
- .github/workflows/release.yaml
- package-lock.json
- packages/cli/bin/dev
- packages/cli/bin/run
- packages/cli/package.json
- packages/cli/src/commands/schema/create.ts
- packages/lib/package.json
- add auto generated release notes to Github release
- repalce remaining process exits
- add missing dev dependency on log4js
> fix: shutdown logger before Node exits

- package.json
- implement workaround for https://github.com/changesets/changesets/issues/421
> ci(changesets): write version bumps to package-lock

- packages/cli/src/__tests__/commands/devices/capability-status.test.ts
- packages/cli/src/commands/devices/capability-status.ts
- packages/cli/src/commands/devices/component-status.ts
- packages/lib/src/__tests__/device-util.test.ts
- packages/lib/src/device-util.ts
- packages/testlib/src/index.ts
> test: add devices:capability-status unit tests

- .changeset/mean-shoes-heal.md
- package-lock.json
- packages/cli/package.json
- packages/lib/package.json
- packages/testlib/package.json
Bump core SDK in preparation for bumping it in the Edge plugin.
> chore: bump core SDK version

- packages/cli/src/__tests__/commands/devices/update.test.ts
> test: add devices:update unit tests

- package-lock.json
- packages/cli/package.json
- packages/cli/src/__tests__/commands/schema.test.ts
- packages/cli/src/commands/schema.ts
- packages/lib/package.json
- packages/testlib/package.json
- update jest types which required bumping ts-jest
- rename a couple variables in schema command file
> test: add schema unit tests

- packages/cli/src/__tests__/commands/schema/create.test.ts
- packages/cli/src/commands/schema/authorize.ts
- packages/cli/src/commands/schema/create.ts
- packages/cli/src/lib/commands/schema/schema-util.ts
- extract default const to util module
> test: add schema:create unit tests

- .changeset/stale-spoons-tell.md
- packages/cli/src/__tests__/commands/schema/update.test.ts
- packages/testlib/src/index.ts
> test: add schema:update unit tests

- packages/cli/README.md
- packages/cli/src/commands/devices/commands.ts
> docs(devices): add examples to help with common parsing errors

- .github/workflows/release.yaml
- .github/workflows/stale.yaml
> ci: Update actions

- .changeset/old-rocks-try.md
- packages/cli/src/__tests__/commands/devices.test.ts
- packages/cli/src/commands/devices.ts
Allow multiple type flags in devices command
> feat: allow multiple type flags in devices command

- packages/cli/README.md
- packages/cli/package.json
- packages/lib/package.json
- packages/testlib/package.json
> docs: add instructions for using installers

- .github/workflows/release.yaml
> ci: fix homebrew formula update job

- packages/cli/doc/configuration.md
Updated docs for hidden flags that were overlooked in the pull request that changed them.
> docs: fix docs for hidden args

- .editorconfig
- .github/workflows/cd.yaml
- .gitignore
- packages/cli/functional-tests/README.md
- packages/cli/functional-tests/requirements.txt
- packages/cli/functional-tests/tests/edge_test.py
- packages/cli/functional-tests/tests/version_test.py
- setup initial functional test framework using pytest
- refactor release workflow into more jobs
- configure functional tests to run on every push to main branch
> ci: add functional tests

- .changeset/proud-cameras-visit.md
- package-lock.json
- package.json
- packages/cli/package.json
> fix: bump plugin-cli-edge

- .github/workflows/cd.yaml
> build: run homebrew job on MacOS

- packages/cli/functional-tests/README.md
recommend venv for python isolation
> docs: recommend venv for python isolation

- .changeset/good-worms-greet.md
- package-lock.json
- packages/cli/package.json
Updated edge plugin in to bring in two bug fixes.
> fix: update edge plugin

- packages/cli/doc/configuration.md
Added documentation for edgeDriverTestDirs config option.
> docs: add documentation for edgeDriverTestDirs config option

- package-lock.json
- packages/cli/package.json
Added help plugin to so error message from not-found plugin is accurate.
> fix: include help plugin

- .changeset/config.json
- .github/workflows/cd.yaml
- CONTRIBUTING.md
- packages/cli/README.md
- packages/cli/src/commands/capabilities/translations.ts
- packages/cli/src/lib/log-utils.ts
- packages/lib/src/cli-config.ts
Switch to `main` for the main branch.
> chore: switch from master to main for main branch

- .changeset/thick-jobs-cover.md
- packages/cli/zip-binaries.mjs
> ci: switch Windows archive format to zip

- package-lock.json
- package.json
- packages/cli/package.json
- packages/edge/package.json
- packages/lib/package.json
- packages/lib/src/api-helpers.ts
- packages/testlib/package.json
- tsconfig.json
> chore: update TypeScript

- .github/workflows/cd.yaml
> ci: fix release files glob pattern

- packages/cli/README.md
- packages/cli/src/__tests__/lib/commands/capabilities-util.test.ts
- packages/cli/src/__tests__/lib/commands/deviceprofiles-util.test.ts
- packages/cli/src/__tests__/lib/commands/devices-util.test.ts
- packages/cli/src/__tests__/lib/commands/rules-util.test.ts
- packages/cli/src/commands/apps.ts
- packages/cli/src/commands/capabilities/presentation.ts
- packages/cli/src/commands/presentation.ts
- packages/cli/src/commands/presentation/device-config.ts
- packages/cli/src/lib/commands/capabilities-util.ts
- packages/cli/src/lib/commands/deviceprofiles-util.ts
- packages/cli/src/lib/commands/devices-util.ts
- packages/cli/src/lib/commands/rules-util.ts
- packages/edge/src/__tests__/lib/commands/drivers-util.test.ts
- packages/edge/src/lib/commands/drivers-util.ts
- packages/lib/src/cli-config.ts
- packages/lib/src/table-generator.ts
- packages/testlib/src/index.ts
Removed "this is summarized" text from code and added it to the README.
> Summary info

- .github/workflows/cd.yaml
quote YAML string that has a comma in it
> build: quote YAML string that has a comma in it

- .github/workflows/cd.yaml
Fixed match pattern to actually work this time.
References:
* https://github.com/softprops/action-gh-release/tree/master/src
* https://www.npmjs.com/package/glob
> build: fix match pattern for github release files

- .changeset/pre.json
- packages/cli/README.md
> build: exit prerelease beta status

- packages/cli/README.md
> docs: add description of CLI to README

- CONTRIBUTING.md
- packages/cli/README.md
- packages/cli/src/__tests__/lib/commands/deviceprofiles-util.test.ts
- packages/cli/src/commands/apps.ts
- packages/cli/src/commands/apps/authorize.ts
- packages/cli/src/commands/apps/create.ts
- packages/cli/src/commands/apps/delete.ts
- packages/lib/src/__tests__/table-generator.test.ts
Updated examples for main `apps` commands.
> docs: update examples for main apps commands

- packages/cli/README.md
- packages/cli/src/lib/commands/history-util.ts
Forgot to run `npm run readme` for last commit.
> docs: update readme from last commit

- .changeset/chatty-trees-bathe.md
- .github/workflows/cd.yaml
Fix Windows MSI build step and add a little debug.
> build: fix Windows MSI build

- .changeset/tasty-hats-perform.md
- .github/workflows/cd.yaml
softprops/action-gh-release@v1 action requires / for path separators now:
https://github.com/softprops/action-gh-release
> build: softprops/action-gh-release@v1 action requires / for path separators now

- package.json
- packages/cli/README.md
- packages/cli/doc/configuration.md
- packages/cli/src/commands/apps/delete.ts
- packages/cli/src/commands/apps/oauth.ts
- packages/cli/src/commands/installedapps/delete.ts
- packages/cli/src/commands/installedschema/delete.ts
- packages/cli/src/commands/schema/delete.ts
This is just some miscellaneous documentation updates that have been sitting in my git stash. I also updated the workspace `build` command to run `npm readme` at the end so ends up with a fully updated readme like when we were using lerna.
> docs: miscellaneous doc updates and corrections

- packages/lib/src/__tests__/util.test.ts
- packages/lib/src/__tests__/validate-util.test.ts
- packages/lib/src/util.ts
- packages/lib/src/validate-util.ts
Added a few more utility functions:
* `sanitize`
* `stringValidateFn`
* `urlValidateFn`
Also included unit tests for new functions.
> feat: include a few more utility functions

- .changeset/strong-donkeys-tell.md
- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- package-lock.json
- packages/cli/package.json
- packages/edge/package.json
- packages/edge/src/__tests__/lib/live-logging.test.ts
- packages/lib/package.json
- packages/lib/src/__tests__/login-authenticator.test.ts
- packages/testlib/package.json
* updated core SDK, axios, and qs dependencies
* required Node 18 and npm 9.5
* updated a couple of unit tests (`live-logging.test.ts` and `login-authenticator.test.ts` to work with updated axios)
> chore: update core SDK, axios and qs dependencies; require Node 18

- .changeset/clean-plums-eat.md
- .changeset/tough-bugs-fix.md
- package-lock.json
- packages/cli/README.md
- packages/cli/package.json
- packages/edge/package.json
- packages/edge/src/__tests__/commands/edge/drivers/logcat.test.ts
- packages/edge/src/commands/edge/drivers/logcat.ts
- packages/lib/package.json
- packages/testlib/package.json
* updated core SDK version in all packages (this resulted in the minor change to the README)
* replaced prompt for IP address with request for a hub from the user and then get the IP address from the device record
* updated corresponding tests
> feat: query user for hub in `edge:drivers:logcat` command

- package-lock.json
- packages/cli/package.json
- packages/cli/src/lib/aws-utils.ts
> chore: update AWS SDK

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
Updated node version in ci and cd workflows
> chore: updated node version in workflows

- packages/cli/src/__tests__/lib/commands/schema-util.test.ts
- packages/cli/src/commands/schema/create.ts
- packages/cli/src/commands/schema/update.ts
- packages/cli/src/lib/commands/schema-util.ts
- packages/lib/src/__tests__/item-input/array.test.ts
- packages/lib/src/__tests__/item-input/command-helpers.test.ts
- packages/lib/src/__tests__/item-input/misc.test.ts
- packages/lib/src/__tests__/item-input/object.test.ts
- packages/lib/src/__tests__/user-query.test.ts
Fleshed out unit tests for previous commit adding Q&A input to `schema:create` command.
> tests: add unit tests for code for Q&A Schema App input

- src/__tests__/lib/log-utils.test.ts
Added some missing checks to `loadLog4jsConfig` unit tests.
> test: flesh out loadLog4jsConfig unit tests

- .changeset/spicy-poems-jog.md
- packages/cli/README.md
- packages/cli/src/__tests__/lib/commands/invites-util.test.ts
- packages/cli/src/__tests__/lib/commands/schema-util.test.ts
- packages/cli/src/commands/apps/delete.ts
- packages/cli/src/commands/devicepreferences/create.ts
- packages/cli/src/commands/invites/schema.ts
- packages/cli/src/commands/invites/schema/check-acceptance.ts
- packages/cli/src/commands/invites/schema/create.ts
- packages/cli/src/commands/invites/schema/delete.ts
- packages/cli/src/lib/commands/apps-util.ts
- packages/cli/src/lib/commands/invites-utils.ts
- packages/cli/src/lib/commands/schema-util.ts
- packages/edge/src/commands/edge/channels/invites/create.ts
- packages/edge/src/lib/endpoints/invites.ts
- packages/lib/src/__tests__/item-input/misc.test.ts
- packages/lib/src/__tests__/user-query.test.ts
- packages/lib/src/__tests__/validate-util.test.ts
- packages/lib/src/item-input/misc.ts
- packages/lib/src/user-query.ts
- packages/lib/src/validate-util.ts
Add support for schema invitations.
> feat: add support for schema app invitations

- .github/workflows/cd.yaml
Specify Python version more specifically so we don't get random newer untested versions trying to run functional tests.
> ci: set Python version for functional tests more specifically

- jest.config.ts
- src/__tests__/lib/cli-config.test.ts
- src/__tests__/lib/file-util.test.ts
- src/__tests__/lib/io-util.test.ts
- src/__tests__/lib/log-utils.test.ts
- src/lib/cli-config.ts
- src/lib/command/input-processor.ts
- src/lib/command/output.ts
- src/lib/io-util.ts
Convert a few more unit tests to ESM.
> test: convert more tests to ESM

- jest.config.ts
- src/__tests__/lib/item-input/array.test.ts
- src/__tests__/lib/item-input/misc.test.ts
- src/__tests__/lib/item-input/object.test.ts
Converted item input tests to ESM format.
> test: convert item input tests to ESM

- jest.config.ts
- src/__tests__/lib/command/input-builder.test.ts
- src/__tests__/lib/command/smartthings-command.test.ts
- src/__tests__/lib/login-authenticator.test.ts
- src/__tests__/lib/table-generator.test.ts
- src/__tests__/test-lib/logger-mock.ts
* created `logger-mock.ts` test util to share code for mocking the logger
* convert `input-builder.test.ts` to ESM
* convert `smartthings-command.test.ts` to ESM
> convert more tests to ESM

- .changeset/green-mangos-pretend.md
- package-lock.json
- packages/cli/package.json
- packages/cli/src/__tests__/commands/schema.test.ts
- packages/cli/src/commands/schema.ts
- packages/edge/package.json
- packages/lib/package.json
- packages/testlib/package.json
Added support for requesting Schema Apps by organization. Most of the code changes were in the core SDK but we need to pass a flag for the "all organizations" option.
Related core SDK pull request:
https://github.com/SmartThingsCommunity/smartthings-core-sdk/pull/243
> feat: add support for listing Schema apps by organization

- .changeset/bright-books-fail.md
Updated changeset to release CLI
> fix: release callback URL port number change

- src/__tests__/lib/item-input/select.test.ts
- src/lib/item-input/select.ts
Added unit tests for item-input `selectDef`.
> test: add unit tests for item-input selectDef

- .changeset/sweet-terms-develop.md
Remove mention of defunct edge plugin from changeset.
> chore: remove mention of edge plugin from changeset
