packages/cli/README.md, packages/cli/src/commands/capabilities/presentation/update.ts
Updated the capabilities:presentation:update command to match standards. Users can either call the command with a specific capability's ID and version or a table of capabilities will be outputted and the user will be prompted to enter the index or id of the specific capability presentation to be updated.
=> update capabilities:presentation:update command

packages/cli/src/commands/installedapps.ts, packages/cli/src/commands/installedapps/delete.ts
Added basic commands for installed apps. There is no create command because apps are installed via either strongman or an OAuth-In journey. There is the possibility of updating the installed app but only to rename it. Putting that off until it can be done with the interactive approach that doesn't require cutting and pasting UUIDs
=> PI-901 Added installed apps list, get, and delete commands

packages/cli/src/commands/config.ts
Added ability to list and get configs, e.g.
```
$ cli config
┌───┬──────────────┬────────┬──────────────────────────────────────┬──────────────────────────────────┐
│ # │ name         │ active │ token                                │ apiUrl                           │
├───┼──────────────┼────────┼──────────────────────────────────────┼──────────────────────────────────┤
│ 1 │ default      │ true   │ f8138ed2-xxxx-495f-a41f-a4726be152b5 │ https://api.smartthings.com      │
│ 2 │ demo-staging │        │ f6d55d94-xxxx-4899-9991-20f891e519b0 │ https://apis.smartthingsgdev.com │
│ 3 │ production   │        │ 1aeb4874-xxxx-46c2-8fd0-8aabf623bb5d │ https://api.smartthings.com      │
│ 4 │ staging      │        │ f8138ed2-xxxx-495f-a41f-a4726be152b5 │ https://apis.smartthingsgdev.com │ …
```
=> PI-936 Added listing of defined config profiles

packages/cli/README.md, packages/cli/src/commands/locations/rooms.ts, packages/cli/src/commands/locations/rooms/delete.ts, packages/cli/src/commands/locations/rooms/update.ts, packages/cli/src/commands/rules.ts, packages/cli/src/commands/rules/create.ts, packages/cli/src/commands/rules/delete.ts, packages/cli/src/commands/rules/update.ts
Added rules CRUD commands:
- Added rules:create command. Users can now create rules using a locationId and a form of input.
- Added rules command to display a list of all rules when called with no rule Id and no locationId. Users can also call the rules command with a rule Id or index from the table to display a particular rule's information. If the command is called with a locationId, the rules of that location will be listed.
- Added rules:update command. Users can now update rules using the rule Id, a form of input, and the locationId.
- Added rules:delete command. Users can now delete rules using the rule Id and locationId. If no rule Id is included, a table containing all of the rules will be outputted and users can choose which rule to be deleted by index or rule Id.
I also updated …
=> add rules CRUD commands

packages/cli/README.md, packages/cli/src/commands/deviceprofiles.ts, packages/cli/src/commands/deviceprofiles/presentation.ts, packages/cli/src/commands/devices/presentation.ts, packages/cli/src/commands/presentation.ts
Fixes to CLI to address issues with device presentation commands and to align it with future direction of the API
* Corrected _presentation_ command arguments to correctly consist of a required `vid` and options `mnmn`
* Added  _devices:presentation_ command to display the presentation of a device
* Added _deviceprofiles:presentation_ command as a convenience to display the presentation of a profile
* Add -v flag to _deviceprofiles_ command to display `vid` and `mnmn` in the list table
=> Fixed device presentation display

packages/cli/README.md, packages/lib/src/io-command.ts
Fixed the dry-run output bug for the create commands. Users can now see their output in yaml via the yaml flag and save the output to a file via the output flag.
=> fix dry-run output bug

packages/cli/README.md, packages/cli/src/commands/apps/oauth.ts, packages/cli/src/commands/apps/settings.ts, packages/cli/src/commands/deviceprofiles/delete.ts, packages/cli/src/commands/deviceprofiles/device-config.ts, packages/cli/src/commands/deviceprofiles/presentation.ts, packages/cli/src/commands/deviceprofiles/publish.ts, packages/cli/src/commands/deviceprofiles/update.ts, packages/cli/src/commands/devices/health.ts, packages/cli/src/commands/devices/presentation.ts, packages/cli/src/commands/devices/status.ts, packages/lib/src/io-command.ts
Started bringing device commands up to current practices but ran into issues with multiple, non-ID arguments that I decided to defer to a second PR.
Also switched a number of commands that display non-definition data for objects such as `apps:oauth` from `ListingOutputAPICommand ` to `SelectingOutputAPICommand` for consistency between commands that accept indexes on the command line (because they don't modify anything) and those that don't. Added an argument check to display a descriptive error message when an index is provided for commands that don't support it (because they modify data) rather than just letting the command fail with a 403, which can be confusing.
=> Devices phase1 and selecting output commands

packages/cli/package.json, packages/lib/package.json, packages/testlib/package.json
* add publishConfig to scoped packages as required by npm (private by default)
See https://github.com/lerna/lerna/issues/1821#issuecomment-551393580 and https://github.com/lerna/lerna/tree/master/commands/publish#publishconfigaccess
=> chore: include publishConfig for scoped packages

.github/workflows/ci-cd.yml
* disable `windows-latest` temporarily while we look into why builds are failing on it
=> chore: disable Windows CI runner

packages/lib/src/cli-config.ts
This is my attempt at making the `cliConfig` truly global so the same object is used in plugins as well as the core commands.
=> make cliConfig truly global

packages/lib/src/cli-config.ts, packages/lib/src/logger.ts, packages/lib/src/login-authenticator.ts
I found a couple more places where things worked differently when the module was linked vs. downloaded from npm. This fixes those.
=> fix: make logManager and credentials work across with plugins

packages/cli/src/commands/capabilities/delete.ts
Fixed a bug where we were passing an empty id to `processNormally` instead of no id when no id was specified on the command line.
=> fix: corrected processing of command line input into command line id

packages/cli/README.md, packages/cli/src/commands/deviceprofiles/create.ts, packages/cli/src/commands/deviceprofiles/update.ts, packages/cli/src/commands/deviceprofiles/view.ts, packages/cli/src/commands/deviceprofiles/view/create.ts, packages/cli/src/commands/deviceprofiles/view/update.ts
Changes to make it easier to work with device profiles, device configurations, and device presentation. Significant changes are:
1. Added to create device profiles with prompt/response process much like capabilities
1. Automatically create a device configuration (and presentations) for device profiles that do not specify a vid
1. Added three device "view" commands to allow device profiles and device configs to be created from one aggregate data definition rather than requiring a series of separate commands.
```
$ smartthings deviceprofiles:create
? Device Profile Name: Duplex Metering Outlet
? Primary capability ID:  switch
? Select an action... Add another capability to this component
? Capability ID:  powerMeter
? Select an action... Add another component
? ComponentId ID:  outlet1
? …
```
=> feat: added prompted device profile creation and device view commands 

packages/cli/README.md, packages/cli/src/commands/apps.ts, packages/cli/src/commands/apps/create.ts, packages/cli/src/commands/apps/register.ts, packages/cli/src/commands/apps/update.ts, packages/cli/src/commands/schema/authorize.ts, packages/cli/src/commands/schema/create.ts, packages/cli/src/commands/schema/update.ts, packages/cli/src/lib/aws-utils.ts, packages/cli/src/lib/common-flags.ts
Several small fixes and enhancements:
* Added flags to `apps` list command to accept filter parameters. 
* Fixed bug in `schema:update` where list selection wasn't working.
* Added flags to app and schema AWS lambda authorization to be able to override default principal and statement-id parameters.
=> feat: app list options and fixes to app and schema commands

package-lock.json, package.json, packages/cli/README.md, packages/cli/package.json, packages/cli/src/commands/deviceprofiles.ts, packages/cli/src/commands/deviceprofiles/create.ts, packages/cli/src/commands/deviceprofiles/update.ts, packages/cli/src/commands/deviceprofiles/view.ts, packages/cli/src/commands/deviceprofiles/view/create.ts, packages/cli/src/commands/deviceprofiles/view/update.ts, packages/cli/src/commands/presentation.ts, packages/cli/src/commands/presentation/device-config.ts, packages/lib/package.json
Note that although there are some code changes here to use `presentationId` and `manufacturerName` in the device config object there is actually no functional change to the CLI at this time.  Also long as the API still accepts `vid` and `mnmn` they will continue to work in device config bodies. With this change, however, the CLI will be ready for whenever the API stops supporting the old names. The rest of these changes here are argument naming and documentation changes.
=> fix: Update to accommodate switch from vid to presentationId

package.json, packages/cli/doc/configuration.md, packages/cli/package.json, packages/cli/src/hooks/init/init-config.ts, packages/lib/package.json, packages/lib/src/__tests__/logger.test.ts, packages/lib/src/__tests__/resources/good-logging.yaml, packages/lib/src/cli-config.ts, packages/lib/src/logger.ts
* use separate logging.xml file for logging configuration instead of reading key from config.yaml file
* removed plain dependencies from main package.json (Lerna doesn't use these anyway) so we don't have to maintain them
* fixed dependency versions for core SDK (they all match now)
=> feat: use separate file for logging config

packages/lib/src/smartthings-command.ts
Added support for accessing the parsed `argv` parameters we are storing in `_argv`. I had to call the accessor something other than `argv` because `argv` is already used to the full unprocessed list of arguments by the parent `Command` class.
=> feat: add support for access to parsed argv property

publish.sh
* Renamed binary files inside to "smartthings" (or "smartthings.exe" for windows)
* removed build directories from path inside zip
=> fix: clean up zip file contents

packages/cli/README.md
* moved `Configuration` down to the bottom of the page; users should seldom need it
* added note about PATs not being useable but not recommended
* remove PAT example
* removed information that was duplicated in docs/configuration.md (including logging info).
=> docs: fix README

packages/cli/package.json
* fixed binary name back to original (from oclif example) `bin/run` (this fixes running the CLI from npm installed package)
* updated pkg tool
* forced inclusion of yarn in binary (this fixes installing plugins from pre-built binary)
=> fix: fix issues with binary and node builds

packages/cli/README.md
* added temporary example of token configuration
* fixed heading for "Configuration and Logging" so it it shows up in the table of contents
=> docs: include temporary token example

.release-it.yaml
* disable release-it changelog so it doesn't override the one generated by lerna
* add a `v` to the title to match lerna
* remove release-it configs that weren't overriding defaults
=> CI(publish): ignore changelog from release-it

packages/cli/README.md, packages/cli/src/commands/capabilities/presentation/create.ts, packages/cli/src/commands/capabilities/presentation/update.ts
Default version to 1 when the id is specified but no version is specified on the command line for both of these commands.
=> fix: use default version of 1 when not id included in command line without version

packages/cli/README.md, packages/cli/src/commands/apps.ts, packages/cli/src/commands/config.ts, packages/cli/src/commands/deviceprofiles.ts, packages/cli/src/commands/devices.ts, packages/cli/src/commands/locations/rooms.ts, packages/cli/src/commands/rules.ts, packages/cli/src/commands/rules/create.ts, packages/cli/src/commands/rules/delete.ts, packages/cli/src/commands/rules/update.ts, packages/lib/src/__tests__/format.test.ts, packages/lib/src/__tests__/output-builder.test.ts, packages/lib/src/__tests__/output.test.ts, packages/lib/src/format.ts, packages/lib/src/output-builder.ts, packages/lib/src/output.ts
* Updated several `ListingOutputAPICommand` commands to use the new `outputListing` functional style.
* Notably un-updated is the `schema` command. I need to figure out how to create a schema app so I can test it first.
* The `config` command no longer has a dependency on `APICommand` which is good since it's not an API command. 😄 
* Fixed `rules` command when looking up a rule by id or index without specifying a location id.
* Commands now use `build(List)TableOutput` before checking the `(listT|t)ableFieldDefinitions`. I didn't actually end up using this but they should be checked in this order since a complex `build(List)TableOutput` method could make use of table field definitions and there is no reason we shouldn't be able to use the default names.
* Moved logic for determining …
=> fix: fix rules lookup without location id and functional refactor

package-lock.json, packages/cli/src/commands/deviceprofiles/presentation.ts, packages/cli/src/commands/presentation.ts, packages/lib/package.json, packages/lib/src/api-command.ts
Implemented a change to pass an `Accept-Language` header in API requests so that endpoints such as `/presentation` will only return one translation rather than all of them. 
By default the language is obtained from the operating system of the computer running the command. There is also a new `language` flag that overrides that value. The flag accepts an ISO language code such as `ko`. If the reserved values `NONE` is passed as the language flag than no  `Accept-Language` is sent. In the case of `/presentation` that returns all available translations.
=> feat: Added support for specifying a language header

packages/cli/src/commands/apps.ts
Fixed typo that prevented display of ARN/URL in verbose apps listing
=> fix: Corrected bug display verbose apps table

packages/cli/README.md, packages/cli/src/commands/apps.ts, packages/cli/src/commands/apps/authorize.ts, packages/cli/src/commands/capabilities.ts, packages/cli/src/commands/capabilities/namespaces.ts, packages/cli/src/commands/capabilities/presentation.ts, packages/cli/src/commands/capabilities/translations.ts, packages/cli/src/commands/deviceprofiles.ts, packages/cli/src/commands/schema.ts, packages/cli/src/commands/schema/authorize.ts, packages/lib/src/io-command.ts
* Removed last use of `ListingOutputAPICommandBase` and `ListingOutputAPICommand` and then removed them.
* Renamed several command classes to use the suffix `Command`. I only did this to only commands that have already been converted to the new functional style and plan to do the rest as I convert them.
* Updated commands that don't use the API (`schema:authorize` and `apps:authorize` to directly use `SmartThingsCommand` instead of `APICommand` which removed some unused flags from their help.
* minor doc fix in `schema` command example
=> refactor: convert last listing commands to functional API, other minor misc clean-up

packages/cli/README.md, packages/cli/src/commands/installedapps.ts, packages/cli/src/commands/installedapps/delete.ts, packages/cli/src/commands/installedapps/rename.ts, packages/cli/src/commands/installedschema.ts, packages/cli/src/commands/installedschema/delete.ts
Added commands to list, show, and delete installed ST schema connector instances. Also updated installed app delete and rename commands to accept location and verbose flags since location is important context for identifying instances that
often have the same names.
=> feat: Added commands to list, show, and delete installed ST schema instances

packages/cli/package.json, packages/cli/src/__tests__/commands/locations.test.ts, packages/lib/package.json, packages/testlib/tsconfig.json
=> test(LocationsCommand): add inital unit tests

packages/cli/README.md, packages/cli/src/commands/capabilities.ts, packages/cli/src/commands/capabilities/create.ts, packages/cli/src/commands/capabilities/translations.ts, packages/cli/src/commands/capabilities/translations/upsert.ts, packages/cli/src/commands/deviceprofiles/translations.ts, packages/cli/src/commands/deviceprofiles/translations/upsert.ts, packages/lib/src/command-util.ts, packages/lib/src/io-command.ts
Updated commands that used `Nested*APICommand` classes to new functional API and removed them.
=> refactor: convert and remove NestedListingOutputAPICommand commands

packages/cli/README.md, packages/cli/src/commands/apps.ts, packages/cli/src/commands/apps/delete.ts, packages/cli/src/commands/apps/oauth.ts, packages/cli/src/commands/apps/oauth/generate.ts, packages/cli/src/commands/apps/oauth/update.ts, packages/cli/src/commands/apps/settings.ts, packages/cli/src/commands/apps/settings/update.ts, packages/cli/src/commands/apps/update.ts, packages/lib/src/__tests__/basic-io.test.ts, packages/lib/src/__tests__/format.test.ts, packages/lib/src/basic-io.ts, packages/lib/src/format.ts, packages/lib/src/input-builder.ts
Converted some of the `SelectingInputOutputAPICommand` commands to the new functional versions. I'm doing this one in multiple steps to keep the pull request size down.
=> refactor: convert more Selecting* commands to functional version

packages/cli/src/__tests__/commands/presentation/device-config.test.ts, packages/cli/src/commands/presentation/device-config.ts
Adds optional second _manufacturerName_ argument to the `presentation:device-config` command so that non-default configurations can be retrieved.
=> feat: Accept manufacturerName in device config command

package-lock.json, packages/cli/package.json
* pin `pkg` to 4.4.9 as [4.5.0](https://github.com/vercel/pkg/releases/tag/4.5.0) seems to have broken our build (built binaries would not have expected OCLIF commands)
=> fix: pin pkg to resolve missing commands

packages/cli/src/commands/schema/authorize.ts, packages/cli/src/commands/schema/create.ts
Use the correct principal when authorizing st schema apps
=> fix: Default schema authorization to the correct principal

packages/cli/src/commands/capabilities.ts, packages/cli/src/commands/deviceprofiles/create.ts, packages/cli/src/commands/schema/authorize.ts, packages/cli/src/commands/schema/create.ts
Corrects a bug in the current implementation that only allows for the selection of custom capabilities in the interactive `deviceprofiles:create` process. That was because a list of only the custom capabilities was displayed, and the entry was validated by checking for membership in the list. Two legitimate scenarios were therefore unsupported:
1. Standard capabilities (the most common case)
2. Custom capabilities that weren't owned by the user (less common but still valid)
Since there are over 200 standard capabilities, prompting with a list of all of them plus any custom capabilities seems needlessly noisy. On the other hand, being able to select from a list is useful, especially for new users. Therefore this change:
* Doesn't initially prompt with a list
* Prompts the user to enter a …
=> fix: Support standard capabilities in interactive profile creation

package-lock.json, packages/cli/README.md, packages/cli/package.json, packages/cli/src/commands/schema/regenerate.ts, packages/lib/package.json
Added schema:regenerate command to re-generate the client ID and client secret for an ST Schema connector.
=> feat: Added schema:regenerate to create new client IDs and secrets

package-lock.json, packages/cli/README.md, packages/cli/package.json
- add support for viewing read-only channels where appropriate
Updated edge plugin to v1.4.0 which includes the ability to view read-only channels where appropriate.
=> feat: update edge plugin to v1.4.0

packages/cli/src/commands/capabilities.ts
The CLI is currently returning an error from the `capabilities` command when the user has no custom capabilities. That's inconsistent with all other list commands that return a "no items found" message.
=> fix: Don't consider lack of custom capabilities an error in list command

packages/cli/src/__tests__/commands/apps.test.ts, packages/cli/src/__tests__/commands/apps/authorize.test.ts, packages/cli/src/__tests__/commands/apps/create.test.ts, packages/cli/src/__tests__/commands/apps/delete.test.ts, packages/cli/src/__tests__/commands/apps/oauth.test.ts, packages/cli/src/__tests__/commands/apps/oauth/generate.test.ts, packages/cli/src/__tests__/commands/apps/oauth/update.test.ts, packages/cli/src/__tests__/commands/apps/register.test.ts, packages/cli/src/__tests__/commands/apps/settings.test.ts, packages/cli/src/__tests__/commands/apps/settings/update.test.ts, packages/cli/src/__tests__/commands/apps/update.test.ts, packages/cli/src/__tests__/commands/devicepreferences/translations.test.ts, packages/cli/src/__tests__/commands/devicepreferences/translations/create.test.ts, packages/cli/src/__tests__/commands/devices.test.ts, packages/cli/src/__tests__/commands/locations.test.ts, packages/cli/src/__tests__/commands/locations/create.test.ts, packages/cli/src/__tests__/commands/locations/delete.test.ts, packages/cli/src/__tests__/commands/locations/rooms.test.ts, packages/cli/src/__tests__/commands/locations/rooms/create.test.ts, packages/cli/src/__tests__/commands/locations/rooms/delete.test.ts, packages/cli/src/__tests__/commands/locations/rooms/update.test.ts, packages/cli/src/__tests__/commands/locations/update.test.ts, packages/cli/src/__tests__/commands/organizations.test.ts, packages/cli/src/__tests__/commands/presentation/device-config.test.ts
- related to https://github.com/oclif/core/issues/330
- pass empty arg arrays to avoid oclif parsing jest flags
=> test: fix unexpected arguments errors

package-lock.json
Revert most package-lock.json changes.
I had removed package-lock.json so it would regenerate but this has caused a problem. I haven't determined exactly what update caused the problem yet so I grabbed the previous package-lock.json and let `npm i` update what needed to be updated.
I'm going to do more research into what specific update caused this. I can reproduce it in the previous version (6c81990e48c9c568ed65efce710954d9c0828be2 from 2021/12/30) but going back to  ae49b75498f1306eafbbfbc4dc78614625747bac from 2021/10/25 I can remove and rebuild package-lock.json without issue.
=> fix: revert most of package-lock.json which had been completely remade with last commit

lerna.json
The intent of this PR is to prepare the repo for a version change from `0.0.0-pre` to `1.0.0-beta`. Once merged, we will locally version at `1.0.0-beta.0` and publish.
=> chore: change preid to beta

.changeset/friendly-maps-learn.md, .github/workflows/release.yaml, package-lock.json, packages/cli/package.json
* Removed command removing lib directory in prepack script.
* Added a little debug to the packaging. We might want to remove this at some point in the future but I think it would be good to leave it in for a couple releases.
=> build: don't remove lib directory in prepack script

packages/cli/README.md
- use absolute URL since the relative link is broken from the root version of the README
=> docs(readme): remove relative link to config doc

.changeset/eleven-mails-march.md, .github/workflows/ci.yaml, packages/lib/src/__tests__/login-authenticator.test.ts, packages/lib/src/login-authenticator.ts
- remove Node 12 from CI matrix since it is unsupported
=> feat: add debug logging to default login

packages/cli/src/commands/devices/update.ts
Correct copy/paste error in description for devices:update. Previous description incorrectly described devices:status instead.
=> fix: correct devices:update description

packages/cli/src/__tests__/commands/schema/authorize.test.ts, packages/cli/src/__tests__/commands/schema/delete.test.ts, packages/cli/src/__tests__/commands/schema/regenerate.test.ts, packages/cli/src/commands/schema/authorize.ts
- refactor schema:authorize command to use addSchemaPermission
=> refactor: finish schema unit test coverage

.changeset/purple-steaks-behave.md, packages/cli/src/__tests__/commands/devices.test.ts, packages/cli/src/__tests__/commands/virtualdevices.test.ts, packages/cli/src/__tests__/commands/virtualdevices/create-standard.test.ts, packages/cli/src/__tests__/commands/virtualdevices/create.test.ts, packages/cli/src/__tests__/commands/virtualdevices/delete.test.ts, packages/cli/src/__tests__/commands/virtualdevices/events.test.ts, packages/cli/src/__tests__/commands/virtualdevices/update.test.ts, packages/cli/src/__tests__/lib/commands/virtualdevices/virtualdevices-util.test.ts, packages/cli/src/commands/locations.ts, packages/cli/src/commands/virtualdevices.ts, packages/cli/src/commands/virtualdevices/create-standard.ts, packages/cli/src/commands/virtualdevices/create.ts, packages/cli/src/commands/virtualdevices/delete.ts, packages/cli/src/commands/virtualdevices/events.ts, packages/cli/src/commands/virtualdevices/update.ts, packages/cli/src/lib/commands/locations/rooms/rooms-util.ts, packages/cli/src/lib/commands/virtualdevices/virtualdevices-util.ts, packages/lib/src/__tests__/select.test.ts, packages/lib/src/basic-io.ts, packages/lib/src/format.ts, packages/lib/src/output.ts, packages/lib/src/select.ts
Added support for creating and generating events for virtual devices. 
Note: Because of all the file name changes, this is a new PR replaces #318, which will be closed.
=> feat: add support for virtual devices

.changeset/slow-gorillas-care.md, packages/cli/src/__tests__/commands/installedapps.test.ts, packages/cli/src/__tests__/commands/installedapps/delete.test.ts, packages/cli/src/__tests__/commands/installedapps/rename.test.ts, packages/cli/src/commands/installedapps.ts, packages/cli/src/commands/installedapps/rename.ts, packages/cli/src/lib/commands/installedapps/installedapps-util.ts, packages/testlib/src/index.ts
- move any exports from command files to util library
=> test(installedapps): add unit tests

.changeset/wet-cherries-wink.md, package-lock.json, packages/cli/package.json, packages/cli/src/__tests__/commands/apps.test.ts, packages/cli/src/__tests__/commands/apps/create.test.ts, packages/cli/src/__tests__/commands/apps/oauth.test.ts, packages/cli/src/__tests__/commands/apps/oauth/generate.test.ts, packages/cli/src/__tests__/commands/apps/oauth/update.test.ts, packages/cli/src/__tests__/commands/apps/register.test.ts, packages/cli/src/__tests__/commands/apps/settings.test.ts, packages/cli/src/__tests__/commands/apps/settings/update.test.ts, packages/cli/src/__tests__/commands/apps/update.test.ts, packages/cli/src/__tests__/lib/commands/apps/apps-util.test.ts, packages/cli/src/commands/apps.ts, packages/cli/src/commands/apps/create.ts, packages/cli/src/commands/apps/oauth/generate.ts, packages/cli/src/commands/apps/oauth/update.ts, packages/cli/src/commands/apps/register.ts, packages/cli/src/commands/apps/settings.ts, packages/cli/src/commands/apps/settings/update.ts, packages/cli/src/commands/apps/update.ts, packages/cli/src/lib/commands/apps/apps-util.ts, packages/lib/package.json, packages/testlib/package.json
- resolve breaking changes in https://github.com/SmartThingsCommunity/smartthings-core-sdk/releases/tag/v5.0.0
=> feat(apps): update core-sdk app models

.changeset/odd-fireants-act.md, package-lock.json, packages/cli/doc/configuration.md, packages/cli/package.json, packages/cli/src/__tests__/lib/commands/apps/apps-util.test.ts, packages/cli/src/__tests__/lib/commands/devices/devices-util.test.ts, packages/cli/src/commands/deviceprofiles.ts, packages/cli/src/commands/virtualdevices/events.ts, packages/lib/package.json, packages/lib/src/__tests__/smartthings-command.test.ts, packages/lib/src/__tests__/table-generator.test.ts, packages/lib/src/output-builder.ts, packages/lib/src/smartthings-command.ts, packages/lib/src/table-generator.ts
Update table output:
- switch to table package which handles international characters properly
- removed compact / expanded command line options
- removed compactTableOutput configuration option
- added group-rows and no-group-rows command line options
- added groupTableOutputRows configuration option
- (lib) completely isolated use of dependency to table-generator.ts
=> feat: update table output

packages/cli/src/__tests__/commands/devices/delete.test.ts, packages/cli/src/commands/devices/delete.ts
Display additional fields in the devices:delete table, including device label, to make it easier for a user to select the correct device to delete.
=> feat: display label when choosing device to delete

packages/cli/src/lib/commands/capabilities-util.ts
When working on unit tests for this function, I noticed a couple of other minor things:
* added "summarized" info to the end of the table output for a capability
* removed unused `multilineObjects` parameter
* handled properties without optional `type` property more gracefully
=> fix: minor updates to capability output

.eslintrc.js, packages/cli/src/commands/deviceprofiles/create.ts, packages/lib/src/basic-io.ts
Add lint rule for spacing around type annotations.
=> build: enforce correct spacing for type annotations

.changeset/long-dryers-nail.md, package-lock.json, packages/cli/package.json, packages/cli/src/__tests__/commands/schema.test.ts, packages/cli/src/__tests__/commands/schema/create.test.ts, packages/cli/src/__tests__/commands/schema/regenerate.test.ts, packages/cli/src/__tests__/commands/schema/update.test.ts, packages/cli/src/commands/schema.ts, packages/lib/package.json
Added user email property to default ST Schema app output table and updated core plugin version
=> feat: added userEmail field to schema apps

.changeset/quick-brooms-develop.md, package-lock.json, packages/lib/src/__tests__/api-command.test.ts, packages/lib/src/__tests__/api-organization-command.test.ts, packages/lib/src/api-command.ts, packages/lib/src/api-organization-command.ts, packages/testlib/package.json
* moved handling of `organization` command line flag and associated configuration option into `APIOrganizationCommand` class
* moved corresponding unit tests
* updated core SDK version in testlib package (was previously updated in lib and cli packages)
See also https://github.com/SmartThingsCommunity/edge-cli-plugin/pull/52 (draft until this pull request is merged and released).
=> refactor: move organization handling into APIOrganizationCommand class

.changeset/late-suits-buy.md, packages/cli/src/__tests__/lib/commands/capabilities-utils.test.ts, packages/cli/src/lib/commands/capabilities-util.ts
* removed superfluous newlines from beginning of capability output
* minor cleanup and refactoring of utility functions to make them a little more testable
* display type for optional arguments to commands the same as required (except still add " (optional)"
* write unit tests for entire capabilities-utils file
=> fix: minor fixes to capabilities table output

packages/cli/src/__tests__/lib/commands/deviceprofiles-util.test.ts, packages/cli/src/commands/deviceprofiles/create.ts, packages/cli/src/commands/deviceprofiles/update.ts, packages/cli/src/commands/deviceprofiles/view.ts, packages/cli/src/commands/deviceprofiles/view/create.ts, packages/cli/src/commands/deviceprofiles/view/update.ts, packages/cli/src/lib/commands/deviceprofiles-util.ts, packages/cli/src/lib/commands/deviceprofiles/create-util.ts, packages/cli/src/lib/commands/deviceprofiles/view-util.ts
* merge two `buildTableOutput` functions for device profiles
* update code that calls them where necessary
* wrote unit tests for merged function
=> refactor: merge two buildTableOutput functions for device profiles

.changeset/short-guests-fry.md, package-lock.json, packages/cli/package.json, packages/cli/src/__tests__/lib/commands/devices-util.test.ts, packages/cli/src/lib/commands/devices-util.ts, packages/lib/package.json, packages/testlib/package.json
Include driver and hub id in default output for virtual devices if present.
=> feat: add info for virtual devices in table output

packages/cli/src/__tests__/lib/commands/deviceprofiles-util.test.ts, packages/cli/src/commands/deviceprofiles/create.ts, packages/cli/src/commands/deviceprofiles/translations.ts, packages/cli/src/commands/deviceprofiles/update.ts, packages/cli/src/commands/deviceprofiles/view/create.ts, packages/cli/src/commands/deviceprofiles/view/update.ts, packages/cli/src/lib/commands/deviceprofiles-util.ts, packages/cli/src/lib/commands/deviceprofiles/create-util.ts
* refactor device profile cleanup methods
* rename them
* combine common code
* make them return new objects (don't modify incoming objects)
* include unit tests
* finish unit tests for all of `deviceprofiles-util` module
* a couple of random case-corrections for command descriptions
=> refactor: clean up cleanup methods for device profiles

.changeset/famous-actors-mix.md, packages/cli/src/__tests__/commands/devices.test.ts, packages/cli/src/__tests__/lib/commands/devices-util.test.ts, packages/cli/src/commands/devices.ts, packages/cli/src/commands/devices/capability-status.ts, packages/cli/src/commands/devices/component-status.ts, packages/cli/src/commands/devices/status.ts, packages/cli/src/lib/commands/devices-util.ts
Refactored devices command to move utility functions into a separate module and added flags to include device health and device status information to device list and get commands.
=> feat: refactored devices command and added health and status flags.

packages/cli/src/__tests__/lib/commands/deviceprofiles/view-util.test.ts, packages/cli/src/commands/deviceprofiles/view.ts, packages/cli/src/commands/deviceprofiles/view/create.ts, packages/cli/src/commands/deviceprofiles/view/update.ts, packages/cli/src/commands/virtualdevices/create.ts, packages/cli/src/lib/commands/deviceprofiles-util.ts, packages/cli/src/lib/commands/deviceprofiles/view-util.ts
* Refactored methods in `view-util.ts` so they don't need `ts-ignore`. Mostly this meant changing their return types and arguments to be a little more explicit.
* The methods in view-utils.ts now return new objects without modifying the originals. (This isn't super important here but it's a good habit.)
* Wrote tests for `view-utils.ts`.
=> refactor: refactor view-utils functions to remove ts-ignore

packages/cli/src/__tests__/commands/devices/commands.test.ts, packages/cli/src/__tests__/commands/virtualdevices/delete.test.ts, packages/cli/src/__tests__/commands/virtualdevices/events.test.ts, packages/cli/src/commands/devices/commands.ts, packages/cli/src/commands/virtualdevices/delete.ts, packages/cli/src/commands/virtualdevices/events.ts
I found a three places where we weren't using `chooseDevices` to select a device and fixed them.
Also fixed a broken unit test.
=> refactor: use chooseDevices more places

.changeset/eight-apricots-lie.md, packages/cli/src/__tests__/commands/devices.test.ts, packages/cli/src/__tests__/commands/devices/history.test.ts, packages/cli/src/__tests__/commands/locations/history.test.ts, packages/cli/src/__tests__/lib/commands/devices-util.test.ts, packages/cli/src/__tests__/lib/commands/history-util.test.ts, packages/cli/src/commands/devices/history.ts, packages/cli/src/commands/locations.ts, packages/cli/src/commands/locations/history.ts, packages/cli/src/lib/commands/history-util.ts, packages/testlib/src/index.ts
Added commands to display device event history for a single device or an entire location
=> feat: added device and location history commands

packages/lib/src/output.ts
Restrict `keyName` to `sort` method to the one of the object's string keys so we don't need the `ts-ignore` comment.
=> refactor: clean up @ts-ignore in sort function

.github/workflows/cd.yaml
=> ci: make installer jobs depend on github release

.changeset/famous-mirrors-smash.md, package-lock.json, packages/cli/functional-tests/tests/edge_test.py, packages/cli/package.json
Updated to most recent edge plugin so edge commands work again.
=> fix: update libraries so edge plugin commands work again

.changeset/seven-donuts-jam.md, packages/cli/src/__tests__/commands/capabilities/translations.test.ts, packages/cli/src/commands/capabilities/translations.ts, packages/cli/src/commands/capabilities/translations/create.ts, packages/cli/src/commands/capabilities/translations/update.ts, packages/cli/src/commands/capabilities/translations/upsert.ts
Fixed bug where capability translations were not output correctly in json and yaml formats
=> fix: fixed bug in capability translation output

packages/cli/src/__tests__/lib/commands/installeddschema-util.test.ts, packages/cli/src/commands/installedschema.ts, packages/cli/src/commands/installedschema/delete.ts, packages/cli/src/lib/commands/installedschema-util.ts
moved installedschema utilities into -util file
=> refactor: move installedschema utilities into -util file

.changeset/stupid-jeans-grab.md, .changeset/wise-baboons-build.md, packages/cli/src/__tests__/commands/installedapps.test.ts, packages/cli/src/__tests__/commands/installedschema.test.ts, packages/cli/src/commands/installedapps.ts, packages/cli/src/commands/installedschema.ts, packages/cli/src/lib/commands/installedapps-util.ts, packages/cli/src/lib/commands/installedschema-util.ts, packages/lib/src/__tests__/api-helpers.test.ts, packages/lib/src/api-helpers.ts, packages/testlib/src/index.ts
* added `withLocation` to add location to a single item (matches/uses `withLocations` which does the same for a list)
* support verbose flag for installedapps and installedschema commands with single item
* added tests for installedschema command
* removed `InstalledAppWithLocation` and `InstalledSchemaAppWithLocation` in favor of `WithNamedLocation`
=> feat: support verbose flag for installedapps and installedschema commands with single item

packages/cli/src/__tests__/commands/locations/rooms.test.ts, packages/cli/src/__tests__/commands/rules.test.ts, packages/cli/src/__tests__/commands/rules/delete.test.ts, packages/cli/src/__tests__/commands/rules/execute.test.ts, packages/cli/src/__tests__/commands/rules/update.test.ts, packages/cli/src/__tests__/lib/commands/locations/rooms-util.test.ts, packages/cli/src/__tests__/lib/commands/rules-util.test.ts, packages/cli/src/commands/locations/rooms.ts, packages/cli/src/commands/rules.ts, packages/cli/src/lib/commands/locations/rooms-util.ts, packages/cli/src/lib/commands/rules-util.ts
Removed `RoomWithLocation` and `RuleWithLocation` in favor of using `WithNamedLocation` interface used elsewhere.
=> refactor: update rooms and rules to use standard WithNamedLocation instead of special objects

.changeset/orange-fireants-hammer.md, packages/cli/src/commands/devices.ts, packages/cli/src/commands/installedapps.ts, packages/cli/src/commands/installedapps/delete.ts, packages/cli/src/commands/installedapps/rename.ts, packages/cli/src/commands/installedschema.ts, packages/cli/src/commands/installedschema/delete.ts, packages/cli/src/commands/locations/rooms.ts, packages/cli/src/commands/locations/rooms/create.ts, packages/cli/src/commands/locations/rooms/delete.ts, packages/cli/src/commands/locations/rooms/update.ts, packages/cli/src/commands/rules.ts, packages/cli/src/commands/rules/create.ts, packages/cli/src/commands/rules/delete.ts, packages/cli/src/commands/rules/execute.ts, packages/cli/src/commands/rules/update.ts, packages/cli/src/commands/scenes.ts, packages/cli/src/commands/virtualdevices.ts, packages/cli/src/commands/virtualdevices/create-standard.ts, packages/cli/src/commands/virtualdevices/create.ts
Added `helpValue` for flags that need UUIDs.
=> docs: include helpValue for flags that need UUIDs

.changeset/two-emus-study.md, packages/lib/src/__tests__/cli-config.test.ts, packages/lib/src/cli-config.ts, packages/testlib/src/index.ts
Added support for removing managed config values. This will be used by the edge plugin when deleting a channel. Draft pull request for that here:
https://github.com/SmartThingsCommunity/edge-cli-plugin/pull/59
- [ x I have added tests to cover my changes
=> feat: add support for removing managed config values

packages/cli/doc/configuration.md
Minor doc fix. We have long since been using a separate config file for logging.
=> docs: remove reference to long gone "logging" config key

.changeset/gorgeous-knives-yell.md
`@smartthings/cli-testlib` didn't get published even though it was changed because I had forgotten to include it in the changeset.
=> fix: add forgotten changeset for testlib

packages/cli/README.md, packages/lib/src/api-command.ts, packages/lib/src/input.ts, packages/lib/src/output-builder.ts, packages/lib/src/smartthings-command.ts
Added a `helpGroup` of `common` to flags that are used across many commands to separate them out in the help output, making it easier to find specific flags.
=> feat: separate flags that are repeated in many command

.changeset/quiet-ligers-count.md, packages/cli/src/commands/capabilities/create.ts
Always include the arguments list for commands in the `capabilities:create` command even though the docs don't say it's required. This is to workaround a 500 error we are currently getting from the server in this case.
=> fix: always include arguments list for capabilities commands in create

.changeset/three-needles-grab.md, package-lock.json, package.json, packages/cli/README.md, packages/cli/package.json, packages/edge/README.md, packages/edge/package.json, packages/lib/package.json, packages/testlib/package.json
* put `ts-node` and `typescript` dependencies back in their individual package directories
* added `repositoryPrefix` to edge package
=> docs: fix source code link in edge docs

packages/cli/src/__tests__/commands/apps.test.ts, packages/cli/src/__tests__/commands/schema.test.ts, packages/cli/src/__tests__/lib/commands/apps-util.test.ts, packages/cli/src/commands/apps.ts, packages/cli/src/commands/schema.ts, packages/cli/src/lib/commands/apps-util.ts, packages/cli/src/lib/commands/devices-util.ts, packages/lib/src/basic-io.ts, packages/lib/src/format.ts, packages/lib/src/output-builder.ts, packages/lib/src/output.ts, packages/lib/src/table-generator.ts
* cleaned up how the `apps` and `schema` commands handle including the ARN/URL in the output to better support upcoming changes to `TableGenerator`
* moved some code from `apps.ts` into util module for easier testing
* included `extends object` a few more places we are expecting an object
* updated/added unit tests for all touched code
=> refactor: clean up types for apps and schema apps

.changeset/six-carrots-repair.md, packages/cli/README.md, packages/edge/README.md, packages/edge/src/__tests__/commands/edge/drivers/installed.test.ts, packages/edge/src/__tests__/lib/commands/channels-util.test.ts, packages/edge/src/commands/edge/drivers/installed.ts, packages/edge/src/lib/commands/channels-util.ts
add --verbose option to edge:drivers:installed command
=> feat: add --verbose option to edge:drivers:installed command

.changeset/selfish-avocados-agree.md, packages/edge/src/lib/commands/channels-util.ts
Removed `description` and `termsOfServiceUrl` from list output for `edge:channels` command.
=> feat: make channels list fit on a reasonably-size screen

.changeset/healthy-roses-ring.md, packages/cli/README.md, packages/cli/src/commands/devicepreferences.ts, packages/cli/src/commands/devicepreferences/create.ts, packages/cli/src/commands/devicepreferences/update.ts, packages/cli/src/commands/deviceprofiles.ts, packages/cli/src/commands/deviceprofiles/create.ts, packages/cli/src/commands/deviceprofiles/delete.ts, packages/cli/src/commands/deviceprofiles/device-config.ts, packages/cli/src/commands/deviceprofiles/presentation.ts, packages/cli/src/commands/deviceprofiles/publish.ts, packages/cli/src/commands/deviceprofiles/translations.ts, packages/cli/src/commands/deviceprofiles/translations/delete.ts, packages/cli/src/commands/deviceprofiles/translations/upsert.ts, packages/cli/src/commands/deviceprofiles/update.ts, packages/cli/src/commands/deviceprofiles/view.ts, packages/cli/src/commands/deviceprofiles/view/create.ts, packages/cli/src/commands/deviceprofiles/view/update.ts, packages/cli/src/commands/locations/rooms.ts, packages/cli/src/commands/locations/rooms/create.ts, packages/cli/src/commands/locations/rooms/delete.ts, packages/cli/src/commands/locations/rooms/update.ts, packages/edge/README.md, packages/edge/src/commands/edge/channels/assign.ts, packages/edge/src/commands/edge/channels/drivers.ts, packages/edge/src/commands/edge/channels/invites.ts, packages/edge/src/commands/edge/channels/invites/accept.ts, packages/edge/src/commands/edge/channels/invites/create.ts, packages/edge/src/commands/edge/channels/invites/delete.ts, packages/edge/src/commands/edge/channels/unassign.ts
Removed command aliases. Justifications for this:
* the aliases add a lot of noise to the command line help and the README
* the `@oclif/plugin-notfound` plugin works much better than it used to and can now help out users in these cases
=> feat: remove command aliases

packages/cli/README.md, packages/edge/README.md, packages/edge/src/__tests__/commands/edge.test.ts, packages/edge/src/commands/edge.ts
I added a basic "edge" command so the help message you get with `smartthings edge` or `smartthings edge --help` would be for the topic rather than the `edge:channels` command.
Ideally `smartthings edge` would display the same usage info `smartthings edge --help` does but I haven't been able to figure out how to do this with oclif yet so for now it simply prints a message suggesting the user run `smartthings edge --help`.
=> docs: add basic "edge" command for better help message

packages/cli/src/__tests__/commands/config/reset.test.ts
fix bug causing test of reset command to fail if SMARTTHINGS_PROFILE was set
=> fix: remove profile dependency from reset test

.changeset/sixty-geckos-hug.md, packages/cli/src/__tests__/commands/devices/commands.test.ts, packages/lib/src/__tests__/basic-io.test.ts, packages/lib/src/__tests__/input-builder.test.ts, packages/lib/src/__tests__/input.test.ts, packages/lib/src/basic-io.ts, packages/lib/src/input.ts
* checked for input before saying stdin has input
* cleaned up affected unit tests a bit
=> fix: check for input before saying stdin has input

.changeset/tough-snakes-allow.md, packages/edge/src/__tests__/commands/edge/channels/delete.test.ts, packages/edge/src/__tests__/lib/commands/channels-util.test.ts, packages/edge/src/__tests__/lib/commands/drivers-util.test.ts, packages/edge/src/commands/edge/drivers/install.ts, packages/edge/src/lib/commands/channels-util.ts, packages/edge/src/lib/commands/drivers-util.ts, packages/lib/src/__mocks__/cli-config.ts, packages/lib/src/__tests__/cli-config.test.ts, packages/lib/src/__tests__/select.test.ts, packages/lib/src/__tests__/test-lib/mock-command.ts, packages/lib/src/cli-config.ts, packages/lib/src/select.ts, packages/lib/src/smartthings-command.ts
* Validated saved default values for hubs and channels before using them).
* If the saved default is valid, inform the user of the default being used
* If the saved default is valid, clear the key from the CLI-managed config file
* The `edge:drivers:install` command no longer uses a saved default channel (using the saved one here doesn't make sense because the list of channels valid for this command is limited to those the chosen hub is enrolled in).
Implements #445
=> feat: validate saved default values for hubs and channels before using them

.changeset/fifty-kiwis-smoke.md, packages/cli/src/__tests__/commands/devices/history.test.ts, packages/cli/src/__tests__/commands/locations/history.test.ts, packages/cli/src/__tests__/lib/commands/history-util.test.ts, packages/cli/src/commands/devices/history.ts, packages/cli/src/commands/locations/history.ts, packages/cli/src/lib/commands/history-util.ts
* updated `devices:history and `locations:history` commands to work with API limit of 300 items per request
* added a soft limit of 6 requests worth of history when querying JSON or YAML output
* If more than 6 requests will be needed, the user is prompted with options of canceling the request, limiting it, or going ahead
* updated some code and unit tests for history-util to achieve 100% code coverage for unit tests of this module
fixes #449
=> feat: allow more history recall when using JSON or YAML output

.changeset/cyan-boats-dream.md, packages/cli/src/__tests__/commands/devices.test.ts, packages/cli/src/__tests__/lib/commands/devices-util.test.ts, packages/cli/src/commands/devices.ts, packages/cli/src/lib/commands/devices-util.ts, packages/lib/src/__tests__/api-helpers.test.ts, packages/lib/src/api-helpers.ts, packages/testlib/src/index.ts
- enable verbose flag when getting a single device
- add helper method to get location and room names for a single item
=> feat: enable verbose when getting device

packages/cli/README.md, packages/cli/src/commands/apps.ts, packages/cli/src/commands/apps/create.ts, packages/cli/src/commands/apps/delete.ts, packages/cli/src/commands/apps/oauth.ts, packages/cli/src/commands/apps/oauth/generate.ts, packages/cli/src/commands/apps/register.ts, packages/cli/src/commands/apps/settings.ts, packages/cli/src/commands/apps/settings/update.ts, packages/cli/src/commands/apps/update.ts, packages/lib/src/api-command.ts
This pull request is an example of how we might add these links to the descriptions of the commands that are backed by API calls.
=> docs: add references to API docs in a couple commands

packages/cli/README.md, packages/edge/README.md, packages/edge/src/commands/edge/drivers/package.ts
Updated description of `assign` and `install` flags in `edge:drivers:package` command to indicate that defaults will be used if they have been previously specified.
=> docs: update description of flags in package command that use defaults

packages/edge/src/__tests__/commands/edge/channels.test.ts, packages/edge/src/__tests__/commands/edge/channels/drivers.test.ts, packages/edge/src/__tests__/commands/edge/channels/metainfo.test.ts, packages/edge/src/__tests__/commands/edge/drivers.test.ts, packages/edge/src/__tests__/commands/edge/drivers/default.test.ts, packages/edge/src/__tests__/commands/edge/drivers/delete.test.ts, packages/edge/src/__tests__/commands/edge/drivers/install.test.ts, packages/edge/src/__tests__/commands/edge/drivers/installed.test.ts, packages/edge/src/__tests__/commands/edge/drivers/logcat.test.ts, packages/edge/src/__tests__/commands/edge/drivers/package.test.ts, packages/edge/src/__tests__/commands/edge/drivers/switch.test.ts, packages/edge/src/__tests__/file-util.test.ts, packages/edge/src/__tests__/lib/commands/drivers-util.test.ts, packages/edge/src/__tests__/lib/commands/drivers/package-util.test.ts, packages/edge/src/__tests__/lib/live-logging.test.ts
A while back we updated the jest config to automatically clear mocks after each test and removed calls to `clearAllMocks` in the code but we did not do this for the edge plugin. Then, when we merged the edge plugin into the CLI, it acquired this config setting but we did not remove the no-longer-necessary calls to `clearAllMocks`. This PR removes those calls.
=> chore: remove calls to jest.clearAllMocks in edge plugin

.changeset/clever-trees-hang.md, packages/cli/src/__tests__/commands/devices/history.test.ts, packages/cli/src/__tests__/commands/locations/history.test.ts, packages/cli/src/commands/devices/history.ts, packages/cli/src/commands/locations/history.ts
* added missing `await` to `getHistory` call
* updated unit tests some but then decided it would probably be worth spending more time researching switching to yargs from oclif
=> fix: fix failure to output JSON or YAML history

.changeset/shy-balloons-unite.md, packages/cli/src/commands/apps/create.ts
* Minor fix to make the icon URL optional in the Q&A create mode.
=> fix: make icon optional in apps:create Q&A mode

.changeset/silent-mirrors-carry.md, packages/cli/src/__tests__/commands/apps/oauth/generate.test.ts, packages/cli/src/commands/apps/create.ts, packages/cli/src/commands/apps/oauth/generate.ts, packages/cli/src/lib/commands/apps-util.ts, packages/lib/src/item-input/command-helpers.ts, packages/lib/src/item-input/defs.ts
* Added Q & A mode to `apps:oauth:generate` command.
* Since this is the first "update" style Q & A command, added `updateFromUserInput` function to `item-input/command-helpers.ts`.
=> feat: add support for Q&A mode to apps:aouth:generate command

package-lock.json, packages/lib/src/__tests__/item-input/array.test.ts, packages/lib/src/item-input/array.ts
* added unit tests for methods in `input-item/array.ts`
* minor updates to tested code
* don't allow deleting an item if there are already the minimum number of items
* when checking for duplicates, allow value being edited to remain unchanged
* construct new context each time we call `buildFromUserInput` (allows unit tests to see different values passed to each call)
* ran `npx browserslist@latest --update-db` to get rid of build warning
=> test: add unit tests for array input types; minor tweaks to tested code

packages/lib/src/__tests__/item-input/object.test.ts, packages/lib/src/item-input/object.ts
* added unit tests for `objectDef` `InputDefinition` creator function
* minor updates to code
* export and rename `TypeData` (renamed to `ObjectTypeData`) so it could be used in tests
* allow items in `inputDefsByProperty` to have `undefined` values
* build new instances of context for each call rather than re-using the same one
=> test: add unit tests for objectDef InputDefinition creator

.changeset/six-pants-press.md, packages/cli/README.md, packages/cli/src/__tests__/commands/apps/update.test.ts, packages/cli/src/commands/apps/create.ts, packages/cli/src/commands/apps/oauth/generate.ts, packages/cli/src/commands/apps/oauth/update.ts, packages/cli/src/commands/apps/update.ts, packages/cli/src/lib/commands/apps-util.ts, packages/lib/src/__tests__/item-input/command-helpers.test.ts, packages/lib/src/__tests__/item-input/defs.test.ts, packages/lib/src/item-input/command-helpers.ts, packages/lib/src/item-input/misc.ts
* add support for Q&A input to `apps:update` command
* add support for Q&A input to `apps:oauth:update` command
* misc. cleanup
=> feat: support Q&A input for apps and app OAuth data

.changeset/violet-moles-think.md, packages/cli/src/__tests__/lib/commands/capabilities-util.test.ts, packages/cli/src/commands/capabilities/presentation.ts, packages/cli/src/commands/deviceprofiles/view.ts, packages/cli/src/lib/commands/capabilities-util.ts
- fix `capabilities:presentation` and `deviceprofiles:view` commands to prompt for user selection if no ID provided
- minor update to utility library for capabilities
=> fix: correct capabilities:presentation and deviceprofiles:view commands

.changeset/happy-moons-study.md, packages/cli/src/__tests__/lib/commands/devices-util.test.ts, packages/cli/src/lib/commands/devices-util.ts
* add new device fields to standard output
* added unit tests for new code
=> feat: add new device fields to standard output

.changeset/selfish-ghosts-chew.md, .changeset/shiny-sheep-sort.md, packages/cli/src/commands/apps/create.ts, packages/cli/src/commands/apps/oauth/generate.ts, packages/cli/src/commands/apps/oauth/update.ts, packages/cli/src/commands/apps/update.ts, packages/cli/src/commands/devicepreferences/create.ts, packages/cli/src/lib/commands/apps-util.ts, packages/edge/src/__tests__/commands/edge/drivers/logcat.test.ts, packages/lib/src/__tests__/item-input/array.test.ts, packages/lib/src/__tests__/item-input/misc.test.ts, packages/lib/src/__tests__/item-input/object.test.ts, packages/lib/src/__tests__/user-query.test.ts, packages/lib/src/api-command.ts, packages/lib/src/item-input/array.ts, packages/lib/src/item-input/defs.ts, packages/lib/src/item-input/misc.ts, packages/lib/src/item-input/object.ts, packages/lib/src/user-query.ts
This adds support for help text on inputs in the new `item-input` module.
Primary changes:
* added support for `helpText` to `askForString` to `askForOptionalString` functions which adds " (? for help)" text to prompt and displays value of `helpText` if the user enters "?"
* added support for `helpText` to `arrayDef`, `checkboxDef` and `objectDef`
* used new `helpText` for these functions in several places
* updated unit tests for updated code
Secondary cleanup:
* renamed `askForString` to `askForOptionalString` and updated calls to it (now matches naming convention used for `optionalStringDef`)
* renamed `askForRequiredString` to `askForString` and updated calls to it (now matches naming convention used for `stringDef`)
* combined code for `askForOptionalString` and `askForString` into a …
=> feat: add help text when entering a redirect URI

.changeset/shiny-bananas-add.md, packages/edge/src/__tests__/lib/commands/drivers/package-util.test.ts, packages/edge/src/commands/edge/drivers/package.ts, packages/edge/src/lib/commands/drivers/package-util.ts
Optionally include `search-parameters.yaml` (or `search-parameters.yml`) in edge driver packages.
=> feat: include search-parameters.yaml in edge driver package

package-lock.json, packages/cli/package.json, packages/edge/package.json, packages/edge/src/__tests__/commands/edge/drivers/default.test.ts, packages/edge/src/commands/edge/drivers/default.ts, packages/lib/package.json, packages/testlib/package.json
Added the ability to display details of standard default edge drivers
=> feat: added detail command for default edge drivers

.changeset/lemon-bottles-beam.md, packages/cli/src/__tests__/commands/virtualdevices/create-standard.test.ts, packages/cli/src/__tests__/commands/virtualdevices/create.test.ts, packages/cli/src/commands/virtualdevices/create-standard.ts, packages/cli/src/commands/virtualdevices/create.ts, packages/cli/src/lib/commands/hubs-util.ts, packages/cli/src/lib/commands/virtualdevices-util.ts
Added support for locally executing virtual devices
=> feat: locally executing virtual devices

.changeset/old-beds-reflect.md, packages/cli/README.md, packages/cli/src/__tests__/lib/commands/locations/modes-util.test.ts, packages/cli/src/commands/locations/modes.ts, packages/cli/src/commands/locations/modes/create.ts, packages/cli/src/commands/locations/modes/delete.ts, packages/cli/src/commands/locations/modes/getcurrent.ts, packages/cli/src/commands/locations/modes/setcurrent.ts, packages/cli/src/commands/locations/modes/update.ts, packages/cli/src/lib/commands/locations/modes-util.ts
Add commands for working with location modes:
- list/get
- create
- update
- delete
- get current
- set current
=> feat: add Modes commands

.changeset/twelve-rings-draw.md, .github/workflows/cd.yaml, .github/workflows/ci.yaml, packages/cli/package.json, packages/edge/package.json, packages/lib/package.json, packages/testlib/package.json
Reverted minimum node version to 18.5.0 for consistency with packaging
=> chore: reverted minimum node version to 18.5.0

.changeset/funny-chicken-marry.md, .changeset/green-fireants-try.md, CONTRIBUTING.md, packages/cli/README.md, packages/cli/src/__tests__/commands/schema/create.test.ts, packages/cli/src/__tests__/commands/schema/update.test.ts, packages/cli/src/commands/apps/create.ts, packages/cli/src/commands/apps/update.ts, packages/cli/src/commands/schema/create.ts, packages/cli/src/commands/schema/update.ts, packages/cli/src/lib/aws-utils.ts, packages/cli/src/lib/commands/schema-util.ts, packages/lib/src/input.ts, packages/lib/src/item-input/array.ts, packages/lib/src/item-input/command-helpers.ts, packages/lib/src/item-input/defs.ts, packages/lib/src/item-input/misc.ts, packages/lib/src/item-input/object.ts, packages/lib/src/user-query.ts, packages/lib/src/validate-util.ts
Add support for Q&A input for Schema Apps.
=> feat: add support for Q&A Schema App input

.changeset/short-timers-exercise.md, packages/lib/src/__tests__/item-input/object.test.ts, packages/lib/src/item-input/command-helpers.ts, packages/lib/src/item-input/defs.ts, packages/lib/src/item-input/misc.ts, packages/lib/src/item-input/object.ts
* Fixed cancel action to actually cancel even when validation errors exist.
=> fix: make cancel action actually cancel even when there are validation errors

.changeset/weak-eagles-drop.md, packages/edge/src/__tests__/commands/edge/drivers/logcat.test.ts, packages/edge/src/commands/edge/drivers/logcat.ts, packages/lib/src/__tests__/sse-command.test.ts, packages/lib/src/sse-command.ts
Moved trapping of interrupt signal (user pressing ctrl-c) to after a connection is made to prevent a hangup trying to tear down close a connection that isn't open yet.
=> fix: fix issue with ctrl-c not working while connecting

.changeset/chilled-dodos-attack.md, packages/edge/src/__tests__/lib/commands/channels-util.test.ts, packages/edge/src/lib/commands/channels-util.ts
fix bug that was preventing channel name from being displayed in some cases
=> fix: fix channel name lookup bug for edge drivers

.changeset/early-houses-sip.md, package-lock.json, packages/cli/package.json, packages/cli/src/__tests__/commands/schema.test.ts, packages/cli/src/commands/schema.ts, packages/cli/src/commands/schema/create.ts, packages/cli/src/commands/schema/delete.ts, packages/cli/src/commands/schema/regenerate.ts, packages/cli/src/commands/schema/update.ts, packages/edge/package.json, packages/lib/package.json, packages/testlib/package.json
Added organization support for ST Schema CRUD commands
=> feat: added organizations to Schema CRUD commands

.changeset/smooth-lamps-shake.md, packages/cli/README.md, packages/edge/src/commands/edge/channels/unassign.ts
Improve channels:unassign prompt text
Update README
=> fix: improve channels:unassign prompt text

.github/workflows/cd.yaml, packages/cli/functional-tests/requirements.txt
Require specific versions of all Python tools used to run functional tests.
=> ci: set specific versions for all functional tests tools

.changeset/brave-cars-grin.md, packages/cli/src/__tests__/lib/commands/history-util.test.ts, packages/cli/src/lib/commands/history-util.ts
* treat integer values for `before` and `after` flags as seconds since the epoch as describe in the help
* refactor: simplified sort function
* refactor: minor reformatting
* refactor: use `confirm` inquirer input type for y/n question instead of text input
* in JSON/YAML output, strictly obey `after`
* the API first returns items after the specified `after` but allows the user to continue on with the "next" page link
* the interactive table format output still allows the user to continue on to view items, as the API does
* when asking for JSON or YAML output, we now strictly obey the `after` flag
=> fix: minor history fixes

src/__tests__/lib/login-authenticator.test.ts
I want to do at least a little more clean-up of these tests but have limited this PR because of the indentation changes due to the removal of the top-level `describe`.
* remove superfluous top-level `describe`
* mock `delay` function from util to wait 10ms
=> test: minor login test cleanup

src/__tests__/lib/login-authenticator.test.ts, src/lib/login-authenticator.ts
* use plain old mock instead of log4js recording logger
* fill in a few missed tests (one block of unreachable code still untested because it's, well, unreachable)
=> test: cleanup and fill-in login-authenticator tests a bit

packages/cli/src/__tests__/commands/apps/create.test.ts, packages/cli/src/__tests__/commands/apps/oauth/generate.test.ts, packages/cli/src/__tests__/commands/apps/update.test.ts, packages/cli/src/__tests__/commands/devices/history.test.ts, packages/cli/src/__tests__/commands/locations/history.test.ts, packages/cli/src/__tests__/commands/schema/update.test.ts, packages/cli/src/commands/devices/history.ts, packages/cli/src/commands/locations/history.ts, src/__tests__/commands/config.test.ts, src/__tests__/lib/cli-config.test.ts, src/__tests__/lib/command/basic-io.test.ts, src/__tests__/lib/command/format.test.ts, src/__tests__/lib/command/input-builder.test.ts, src/__tests__/lib/command/input-processor.test.ts, src/__tests__/lib/command/output-builder.test.ts, src/__tests__/lib/command/output.test.ts, src/__tests__/lib/io-util.test.ts, src/commands/config.ts, src/lib/command/input-processor.ts, src/lib/command/output-builder.ts, src/lib/command/output.ts, src/lib/io-util.ts
Converted `IOFormat` enum to a simple type.
=> refactor: convert IOFormat enum to simple type

jest.config.ts, packages/cli/src/__tests__/lib/commands/virtualdevices-util.test.ts, packages/cli/src/lib/commands/virtualdevices-util.ts, src/__tests__/lib/command/input-builder.test.ts, src/__tests__/lib/command/input-processor.test.ts, src/lib/command/input-builder.ts, src/lib/command/input-processor.ts
* convert classes from `input-processor.ts` to simple functions
* updated unit tests for this code both for the new functions and for ESM
* 100% coverage of `input-processor.ts` now
* misc. minor test cleanup
Note that some tests that haven't yet been converted to ESM and thus are not running have been touched via search-and-replace. More will be done to these in future PRs when they are converted to ESM.
=> refactor: convert classes in input-processor.ts to simple functions

packages/cli/src/__tests__/commands/apps/create.test.ts, packages/cli/src/__tests__/commands/apps/settings.test.ts, packages/cli/src/__tests__/commands/devices.test.ts, packages/cli/src/__tests__/commands/devices/update.test.ts, packages/cli/src/__tests__/commands/rules/execute.test.ts, packages/cli/src/__tests__/commands/virtualdevices/update.test.ts, packages/edge/src/__tests__/commands/edge/channels/metainfo.test.ts, packages/edge/src/__tests__/commands/edge/drivers.test.ts, src/__tests__/lib/command/output.test.ts, src/__tests__/lib/table-generator.test.ts, src/lib/command/smartthings-command.ts, src/lib/table-generator.ts
* converted `DefaultTableGenerator` and `Table` classes to functions
* `defaultTableGenerator` now takes an `options` object (with only `groupRows` as an option) instead of the `groupRows` boolean
* updated unit tests, including adding a little more coverage
=> refactor: convert classes in table-generator.ts to functions

jest.config.ts, src/__tests__/lib/command/output.test.ts, src/lib/command/output.ts
* convert tests in `output.test.ts` to ESM
* fixed "handles includeIndex" test to use mock of table generator
* changed code under test to use arrow functions
=> test: convert output.test.ts to ESM

jest.config.ts, src/__tests__/lib/command/api-command.test.ts, src/__tests__/lib/command/api-organization-command.test.ts, src/lib/command/api-command.ts
* update `api-organization-command.test.ts` to ESM
* some minor updates to `api-command.test.ts` so it matches this one and they are both more complete
=> test: convert api-organization-command.test to ESM

jest.config.ts, src/__tests__/lib/command/listing-io.test.ts, src/__tests__/lib/command/output-builder.test.ts, src/__tests__/lib/command/select.test.ts, src/lib/command/select.ts
converted listing-io, output-builder, and select tests to ESM
=> test: convert listing-io, output-builder, and select tests to ESM

jest.config.ts, src/__tests__/lib/command/util/apps-util.test.ts, src/__tests__/lib/command/util/devicepreferences-util.test.ts
Converted apps-util.test.ts and devicepreferences-util.test.ts tests to ESM.
=> test: convert apps-util and devicepreferences-util tests to ESM

jest.config.ts, src/__tests__/commands/config.test.ts
* convert the last test currently running on the yargs branch to work with ESM
* added a few more tests to config.test.ts to get more complete coverage
* updated the HTML output for tests to use dark mode (unfortunately, this doesn't cover the coverage reports which are blinding me 😄)
=> test: convert config.test.ts to ESM

src/__tests__/commands/devicepreferences.test.ts, src/commands/devicepreferences.ts
* added unit tests for `devicepreferences` command
* fixed reference to value for `--all-organization` option in `devicepreferences` command (not marked as a "fix" because the code with the bug was never released)
=> test: add unit tests for devicepreferences command

packages/cli/src/__tests__/lib/commands/devices-util.test.ts, packages/cli/src/__tests__/lib/commands/history-util.test.ts, packages/cli/src/__tests__/lib/commands/locations/modes-util.test.ts, packages/cli/src/__tests__/lib/commands/locations/rooms-util.test.ts, packages/cli/src/__tests__/lib/commands/rules-util.test.ts, packages/cli/src/__tests__/lib/commands/virtualdevices-util.test.ts, packages/edge/src/__tests__/lib/commands/channels-util.test.ts, packages/edge/src/__tests__/lib/commands/drivers/package-util.test.ts, packages/edge/src/__tests__/lib/live-logging.test.ts, packages/lib/src/__tests__/device-util.test.ts, packages/lib/src/__tests__/sse-io.test.ts, src/__tests__/lib/cli-config.test.ts, src/__tests__/lib/command/select.test.ts, src/__tests__/lib/file-util.test.ts
Removed redundant top-level describe we had been using in many tests.
(I skipped tests for commands since they will be almost complete rewrites anyway with yargs.)
=> refactor: remove extra top-level describe in some tests

.changeset/sweet-dryers-help.md, packages/cli/src/__tests__/lib/commands/schema-util.test.ts, packages/cli/src/lib/commands/schema-util.ts
The function `webHookUrlDef` function builds the input definition for the webhook URL. It needs the initial value of the app when used to edit a pre-existing app but it wasn't being passed in.
=> fix: fix bug with editing webook URL for webhook endpoint app

src/__tests__/lib/cli-config.test.ts, src/__tests__/lib/command/api-command.test.ts, src/__tests__/lib/command/api-organization-command.test.ts, src/__tests__/lib/command/select.test.ts, src/__tests__/lib/command/smartthings-command.test.ts, src/__tests__/lib/file-util.test.ts, src/__tests__/lib/io-util.test.ts, src/__tests__/lib/log-utils.test.ts, src/__tests__/lib/util.test.ts, src/lib/cli-config.ts, src/lib/command/api-command.ts, src/lib/command/api-organization-command.ts, src/lib/command/select.ts, src/lib/command/smartthings-command.ts
* move config helper functions from `smartthings-command.ts` to `cli-config.ts`
* updated unit tests appropriately
* updated uses of these helper functions and their unit tests
* added a couple more unit tests
=> refactor: move config helpers to config

.changeset/bright-books-fail.md, packages/lib/src/__tests__/validate-util.test.ts, packages/lib/src/validate-util.ts
=> fix: allow port number in callback URLs of API_ONLY apps

.github/workflows/cd.yaml
I just merged a [dependabot pull request](https://github.com/SmartThingsCommunity/smartthings-cli/pull/618) that bumped the download-artifact github action from 3 to 4.
It turns out there is a [breaking change](https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes) with v4 that it won't allow downloads of artifacts uploaded with <v4 of upload-artifacts. This pull request updates upload-artifacts.
I also noticed there is another dot release for download-artifacts to I updated that as well.
=> chore: update upload-artifact github action

package-lock.json, package.json
log4js now has its types directly in its own repo and the DefinitelyTyped ones are gone. This removes the DefinitelyTyped ones from our package.json.
=> chore: remove reference to DefinitelyTyped log4js types

src/__tests__/lib/command/command-util.test.ts, src/__tests__/lib/command/util/apps-util.test.ts, src/__tests__/lib/command/util/locations-util.test.ts, src/__tests__/lib/command/util/util-util.test.ts, src/lib/command/command-util.ts, src/lib/command/util/apps-util.ts, src/lib/command/util/locations-util.ts, src/lib/command/util/util-util.ts
Moved all the supporting types and variables for `createChooseFn` into the same file as `createChooseFn`. Not sure why I didn't do this when I created `createChooseFn`. Also updated affected unit tests.
=> refactor: consolidate all choose function stuff in util-utils.ts

.changeset/fuzzy-ants-burn.md, packages/cli/src/__tests__/commands/schema.test.ts, packages/cli/src/__tests__/commands/schema/update.test.ts, packages/cli/src/commands/invites/schema.ts, packages/cli/src/commands/invites/schema/create.ts, packages/cli/src/commands/schema.ts, packages/cli/src/commands/schema/update.ts, packages/cli/src/lib/commands/organization-util.ts, packages/cli/src/lib/commands/schema-util.ts
Force user to choose organization for schema app before doing anything that will automatically assign one.
I will update unit tests more after merge to yargs branch.
=> feat: Force user to choose organization for schema app before doing anything that will automatically assign one

.changeset/late-feet-retire.md, packages/cli/src/commands/schema/update.ts
Schema apps that have a "review" `certificationStatus` cannot be updated.
=> fix: schema apps in "review" state cannot be updated

src/__tests__/commands/apps.test.ts, src/__tests__/commands/devices/capability-status.test.ts, src/__tests__/commands/devices/preferences.test.ts, src/__tests__/commands/locations.test.ts, src/__tests__/commands/locations/create.test.ts, src/__tests__/commands/locations/delete.test.ts, src/__tests__/commands/locations/update.test.ts, src/__tests__/lib/command/api-organization-command.test.ts, src/__tests__/test-lib/api-command-mock.ts
This an example of an attempt at making the unit tests a little less repetitive.
=> refactor: add canned mock of exports from api-command

src/__tests__/lib/command/util/schema-util.test.ts, src/lib/command/util/schema-util.ts
* Added unit test for new `getSchemaAppEnsuringOrganization` function.
* Removed unnecessary generic specification for `APICommand` (which already default to `APICommandFlags`).
=> test: add unit tests for getSchemaAppEnsuringOrganization

src/__tests__/commands/locations/create.test.ts, src/__tests__/lib/cli-config.test.ts, src/__tests__/lib/command/input-and-output-item.test.ts, src/__tests__/lib/command/input-item.test.ts, src/__tests__/lib/command/output-list.test.ts, src/__tests__/lib/command/util/apps-util.test.ts, src/__tests__/lib/command/util/capabilities-util.test.ts, src/__tests__/lib/command/util/devices-util.test.ts, src/__tests__/lib/command/util/schema-util.test.ts, src/__tests__/lib/file-util.test.ts, src/__tests__/lib/io-util.test.ts, src/__tests__/lib/log-utils.test.ts, src/lib/cli-config.ts, src/lib/command/input-item.ts, src/lib/command/output-list.ts, src/lib/command/util/capabilities-util.ts, src/lib/command/util/devices-util.ts, src/lib/command/util/scenes-util.ts, src/lib/command/util/schema-util.ts, src/lib/file-util.ts, src/lib/io-util.ts, src/lib/item-input/object.ts, src/lib/log-utils.ts
* standardize on using `fatalError` for handling fatal error messages the user can be expected to encounter
* updated unit tests (in some cases I modernized them a bit as well but I stopped doing this at some point)
* some bad unit tests were cleaned up a bit in the process (the tests for `input-and-output-item.ts` were particularly messed up
* changed mocking of `fatalError` to return the string `never return` instead of throwing an exception
=> refactor: standarzie on fatalError for handling expected fatal errors

.github/workflows/cd.yaml
The `qemu` umbrella package was split into component packages a long time ago, but the package name itself remained in older registries and just didn't do anything.  Now that the workflow is running on the `ubuntu-24.04` image instead of an older version of Ubuntu, that name is no longer in the registry and trying to install it causes an error.
=> build: remove qemu dummy package reference

.github/workflows/cd.yaml, packages/cli/wix/smartthings.wxs
- Correct the Windows installation folder from the 32-bit folder to the 64-bit folder
- Add a switch to tell the toolset this is a 64-bit build rather than the default 32-bit build.
Changing the folder reference should fix the installation location issue.  I'm not sure the `-arch` switch is necessary for this build I don't think it will hurt, and there may be other incorrect 32-bit things that the installer is doing that no one's noticed yet.
=> build: fix Windows installation location to x64 folder

package-lock.json, package.json, src/__tests__/commands/config.test.ts, src/__tests__/lib/command/api-command.test.ts, src/__tests__/lib/command/smartthings-command.test.ts, src/__tests__/lib/file-util.test.ts, src/__tests__/lib/yargs-transition-temp.test.ts, src/commands/config.ts, src/lib/command/api-command.ts, src/lib/command/smartthings-command.ts, src/lib/file-util.ts, src/lib/yargs-transition-temp.ts, temporary-notes.md
* made use of `env-path` node library to determine where to locate:
* config files (files power users might edit)
* default log file location
* data files (non-user files managed completely by the CLI)
* temporarily included code to find old files and copy them; the plan is to leave this in for at least a year after the yargs release
* the `config` command now tells the user where the config file is found
* updated and added unit tests
=> refactor: use env-paths library to determine file locations

src/__tests__/commands/devices/capability-status.test.ts, src/__tests__/commands/devices/delete.test.ts, src/__tests__/commands/devices/preferences.test.ts, src/__tests__/commands/locations/delete.test.ts, src/__tests__/lib/command/util/devices-choose.test.ts, src/__tests__/lib/command/util/devices.test.ts, src/commands/devices/capability-status.ts, src/commands/devices/commands.ts, src/commands/devices/delete.ts, src/commands/devices/preferences.ts, src/lib/command/util/devices-choose.ts, src/lib/command/util/devices-table.ts, src/lib/command/util/devices.ts
This pull request splits the devices-util module up:
* choose functionality moved to `devices-choose`
* table definitions moved to `devices-table`
* dropped `-util` from name since this is already nested under a `util` directory
* updated calling code and tests
=> refactor: split devices-util up to match new util structure

.changeset/lazy-lies-boil.md, packages/cli/src/lib/commands/organization-util.ts, packages/cli/src/lib/commands/schema-util.ts
Include label in addition to name when prompting the user for an organization. (There are two places we do this.) We should probably run them both through `chooseOrganization` but I'll leave that change for another day.
=> feat: include label when asking user for an organization

package-lock.json, package.json, src/__tests__/commands/config/reset.test.ts, src/__tests__/commands/installedapps/rename.test.ts, src/__tests__/lib/command/util/hub-drivers.test.ts, src/__tests__/lib/item-input/command-helpers.test.ts, src/__tests__/lib/item-input/misc.test.ts, src/__tests__/lib/user-query.test.ts, src/__tests__/lib/validate-util.test.ts, src/commands/config/reset.ts, src/commands/devicepreferences/create.ts, src/commands/installedapps/rename.ts, src/lib/command/util/hub-drivers.ts, src/lib/item-input/command-helpers.ts, src/lib/item-input/defs.ts, src/lib/item-input/misc.ts, src/lib/user-query.ts, src/lib/validate-util.ts
* added new inquirer dependency
* updated `user-query` module
* use new inquirer
* gave functions better names
* made their APIs more consistent with each other
* custom validators for number and integer functions now take `number | undefined` instead of `string` and the query function does the number validation before passing the input on to custom validator as a number
* fixed issue that `urlValidateFn` was allowing URLs missing a `/` like `https:/invalid-url.com`
The old inquirer is still included. A second PR will update the rest of the code and remove it entirely.
=> refactor: update user-query functions to use new inquirer

src/__tests__/lib/user-query.test.ts, src/commands/capabilities/create.ts, src/lib/user-query.ts
* updated `capabilities:create` command to use new inquirer
=> refactor: update capabilities:create command to use new inquirer

src/__tests__/lib/command/util/apps-input-primitives.test.ts, src/__tests__/lib/item-input/array.test.ts, src/__tests__/lib/item-input/command-helpers.test.ts, src/__tests__/lib/item-input/misc.test.ts, src/__tests__/lib/item-input/object.test.ts, src/__tests__/lib/item-input/select.test.ts, src/lib/command/util/apps-input-primitives.ts, src/lib/item-input/array.ts, src/lib/item-input/command-helpers.ts, src/lib/item-input/defs.ts, src/lib/item-input/misc.ts, src/lib/item-input/object.ts, src/lib/item-input/select.ts
* updated `item-input` module to use new inquirer
* updated associated unit tests
=> refactor: update item-input module to use new inquirer

.github/workflows/cd.yaml, .github/workflows/ci.yaml, CONTRIBUTING.md, package-lock.json, package.json
=> chore: update Node to v24

.changeset/spotty-books-taste.md, packages/cli/src/commands/apps/update.ts
When there is no icon image set, editing an app failed because the whole `iconImage` field was missing. Added an empty object if `iconImage` is not present.
=> fix: fix bug preventing editing of apps with no icon image set

src/__tests__/lib/command/util/virtualdevices.test.ts, src/lib/command/util/virtualdevices.ts
* updated virtual devices commands to use new inquirer
=> refactor: update to new inquirer for virtualdevices commands

src/__tests__/lib/command/command-util.test.ts, src/__tests__/lib/command/select.test.ts, src/__tests__/lib/command/util/history.test.ts, src/lib/command/command-util.ts, src/lib/command/select.ts, src/lib/command/util/history.ts
Converted more code to use the new inquirer and updated its unit tests.
=> refactor: convert more code to use new inquirer
